export default [
  {
    id: 'chords-triads-01',
    title: 'Triads: Major, Minor, Diminished, and Augmented',
    track: 'chords',
    kind: 'theory_lesson',
    difficulty: 2,
    tags: ['triads', 'harmony', 'chords'],
    prerequisites: ['intervals-01'],
    estimateMinutes: 5,
    body: 'A triad is a three-note chord built by stacking thirds above a root. A major triad has a major third below a minor third (root–major 3rd–perfect 5th): C–E–G. A minor triad flips the first third to minor (root–minor 3rd–perfect 5th): A–C–E. These two qualities cover most accompaniment in folk and trad music.\n\nDiminished triads use two minor thirds (root–minor 3rd–diminished 5th) and sound tense and unstable. Augmented triads use two major thirds (root–major 3rd–augmented 5th) and appear less often but colour certain passing harmonies. On guitar or piano, knowing triad shapes in the keys you play lets you comp behind a melody without reading full scores.\n\nRoman numerals often label triads by scale degree: I is major in major keys, ii minor, iii minor, IV major, V major, vi minor, vii° diminished. Matching a tune’s home key to its diatonic triads is the first step toward playing useful session backup.',
    tryThis: '',
    quizzes: [
      {
        id: 'chords-triads-01-q1',
        type: 'mcq',
        prompt: 'Which notes form a C major triad?',
        difficulty: 2,
        choices: [
          { id: 'a', text: 'C–E–G', correct: true },
          { id: 'b', text: 'C–E♭–G' },
          { id: 'c', text: 'C–F–A' },
          { id: 'd', text: 'C–D–G' },
        ],
        explain: 'A major triad stacks a major third (C–E) and a minor third (E–G) above the root C.',
      },
      {
        id: 'chords-triads-01-q2',
        type: 'mcq',
        prompt: 'A minor triad differs from a major triad because its:',
        difficulty: 2,
        choices: [
          { id: 'a', text: 'Third above the root is a semitone smaller', correct: true },
          { id: 'b', text: 'Fifth above the root is always diminished' },
          { id: 'c', text: 'Root is lowered by a semitone' },
          { id: 'd', text: 'Third and fifth are both major' },
        ],
        explain: 'Minor triads have a minor third above the root (three semitones) instead of a major third (four semitones).',
      },
    ],
  },
  {
    id: 'chords-inversions-01',
    title: 'Triad Inversions and Bass Notes',
    track: 'chords',
    kind: 'theory_lesson',
    difficulty: 3,
    tags: ['inversions', 'bass', 'chords'],
    prerequisites: ['chords-triads-01'],
    estimateMinutes: 5,
    body: 'A triad in root position places the root in the bass (C–E–G for C major). First inversion puts the third in the bass (E–G–C), often written C/E. Second inversion puts the fifth in the bass (G–C–E), written C/G. The chord symbol stays the same because the pitch class collection is unchanged — only the lowest note moves.\n\nInversions affect voice leading and bass motion. A descending bass line C–B–A–G might use C, G/B, Am, G/C shapes on guitar or keyboard. Inversions also change which melody notes sit on top, helping accompanists avoid clashing with a fiddle line. Figured-bass numbers (6 for first inversion, 6/4 for second) appear in classical sources but modern chord charts use slash notation.\n\nTrad accompanists often choose inversions by ear to keep the right hand or picking pattern close to the previous chord shape. Smooth bass motion makes sets feel cohesive even when the harmonic rhythm is simple I–V–I patterns.',
    tryThis: '',
    quizzes: [
      {
        id: 'chords-inversions-01-q1',
        type: 'mcq',
        prompt: 'C/E (C with E in the bass) is which inversion of C major?',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'First inversion', correct: true },
          { id: 'b', text: 'Root position' },
          { id: 'c', text: 'Second inversion' },
          { id: 'd', text: 'Not an inversion of C major' },
        ],
        explain: 'When the third of the triad (E in C major) is the lowest note, the chord is in first inversion.',
      },
      {
        id: 'chords-inversions-01-q2',
        type: 'truefalse',
        prompt: 'A chord inversion changes the chord’s letter name (e.g., C major stays C major).',
        difficulty: 3,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Inversions rearrange the same three pitch classes; the root and chord quality determine the symbol, while slash notation shows the bass note.',
      },
    ],
  },
  {
    id: 'chords-sevenths-01',
    title: 'Seventh Chords and Their Qualities',
    track: 'chords',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['sevenths', 'jazz', 'harmony'],
    prerequisites: ['chords-triads-01'],
    estimateMinutes: 5,
    body: 'Adding a seventh above the root creates richer four-note chords. A major seventh (maj7) stacks a major triad with a major seventh: C–E–G–B. A dominant seventh (7) uses a minor seventh above the root: C–E–G–B♭ — the V7 chord that strongly pulls to I in major keys. A minor seventh (m7) combines a minor triad with a minor seventh: D–F–A–C.\n\nHalf-diminished (m7♭5) and fully diminished (dim7) sevenths appear in minor-key harmony and jazz turnarounds. In trad contexts, plain dominant sevenths colour céilí band voicings and American-influenced folk songs; maj7 chords appear more in contemporary arrangements than in strict Irish session backup.\n\nRecognising seventh-chord quality by ear helps you choose substitute shapes on guitar or accordion. The third and seventh of a chord (the “guide tones”) define its function even when the root is omitted in a dense mix.',
    tryThis: '',
    quizzes: [
      {
        id: 'chords-sevenths-01-q1',
        type: 'mcq',
        prompt: 'A G7 chord contains which seventh above G?',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'F (minor seventh)', correct: true },
          { id: 'b', text: 'F♯ (major seventh)' },
          { id: 'c', text: 'E (minor seventh)' },
          { id: 'd', text: 'A (major ninth)' },
        ],
        explain: 'Dominant seventh chords use a minor seventh interval above the root: G to F is ten semitones (a minor seventh).',
      },
      {
        id: 'chords-sevenths-01-q2',
        type: 'mcq',
        prompt: 'Which seventh chord type is built on the fifth degree of a major key and pulls strongly to I?',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'Dominant seventh (V7)', correct: true },
          { id: 'b', text: 'Major seventh (Imaj7)' },
          { id: 'c', text: 'Minor seventh (ii7)' },
          { id: 'd', text: 'Fully diminished seventh (vii°7)' },
        ],
        explain: 'The dominant seventh chord on scale degree 5 contains the leading tone tendency and tritone that resolve to the tonic.',
      },
    ],
  },
  {
    id: 'chords-diatonic-major-01',
    title: 'Diatonic Triads in Major Keys',
    track: 'chords',
    kind: 'theory_lesson',
    difficulty: 3,
    tags: ['diatonic', 'major', 'roman-numerals'],
    prerequisites: ['chords-triads-01', 'scales-major-01'],
    estimateMinutes: 5,
    body: 'Diatonic triads are built on each degree of the major scale using only notes from that scale. In G major the pattern is: I (G), ii (Am), iii (Bm), IV (C), V (D), vi (Em), vii° (F♯dim). Capital numerals mean major; lowercase mean minor; ° marks diminished.\n\nThe I, IV, and V chords are primary harmonies in countless folk songs and dance tunes. vi (relative minor) is nearly as common — think of the emotional shift in songs that move between I and vi. ii often precedes V in slightly more sophisticated progressions. vii° is rare in bare trad backup but appears in classical arrangements.\n\nWhen guessing chords for a tune in D major, start with D, G, A, and Bm. If the melody emphasises B and D over an F♯ in the bass, you may be on the V chord. Mapping melody notes to chord tones is a practical session skill that grows directly from this diatonic chart.',
    tryThis: '',
    quizzes: [
      {
        id: 'chords-diatonic-major-01-q1',
        type: 'mcq',
        prompt: 'In the key of G major, what is the vi chord?',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'Em', correct: true },
          { id: 'b', text: 'Am' },
          { id: 'c', text: 'Bm' },
          { id: 'd', text: 'C' },
        ],
        explain: 'vi is built on the sixth scale degree: in G major that is E, forming an E minor triad (E–G–B).',
      },
      {
        id: 'chords-diatonic-major-01-q2',
        type: 'mcq',
        prompt: 'Which Roman numeral pattern describes triads in a major key?',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'I ii iii IV V vi vii°', correct: true },
          { id: 'b', text: 'I II III IV V VI VII (all major)' },
          { id: 'c', text: 'i ii° III iv v VI VII' },
          { id: 'd', text: 'I iv V VI (no minor chords)' },
        ],
        explain: 'Major-key diatonic triads follow major-minor-minor-major-major-minor-diminished on degrees 1 through 7.',
      },
    ],
  },
  {
    id: 'chords-diatonic-minor-01',
    title: 'Diatonic Harmony in Minor Keys',
    track: 'chords',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['diatonic', 'minor', 'harmony'],
    prerequisites: ['scales-minor-01', 'chords-diatonic-major-01'],
    estimateMinutes: 5,
    body: 'Minor-key harmony draws on natural, harmonic, and melodic minor scales, so the available chords shift more than in major. In A natural minor: i (Am), ii° (Bdim), III (C), iv (Dm), v (Em), VI (F), VII (G). Harmonic minor raises the seventh degree, making V a major chord (E major in A minor) with a strong pull to i.\n\nThe raised seventh is why minor-key tunes often end with E→Am rather than Em→Am in A minor. III and VI (C and F in A minor) are common modal-flavoured pivots in folk melody. VII (G major) can feel mixolydian when emphasised over an A drone.\n\nAccompanists in minor keys should listen for whether the tune uses the raised seventh in cadences. Irish and Scottish minor-mode tunes often blend aeolian and dorian flavours without announcing which textbook scale they follow.',
    tryThis: '',
    quizzes: [
      {
        id: 'chords-diatonic-minor-01-q1',
        type: 'mcq',
        prompt: 'In A harmonic minor, what quality is the V chord?',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'E major', correct: true },
          { id: 'b', text: 'E minor' },
          { id: 'c', text: 'Em7' },
          { id: 'd', text: 'E diminished' },
        ],
        explain: 'Harmonic minor raises the seventh degree (G♯ in A minor), making the fifth-degree triad major: E–G♯–B.',
      },
      {
        id: 'chords-diatonic-minor-01-q2',
        type: 'truefalse',
        prompt: 'In natural minor, the triad on scale degree ii is diminished.',
        difficulty: 4,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Built on the second degree of natural minor, the ii chord stacks two minor thirds, yielding a diminished triad.',
      },
    ],
  },
  {
    id: 'chords-extensions-01',
    title: 'Chord Extensions: 9ths, 11ths, and 13ths',
    track: 'chords',
    kind: 'theory_lesson',
    difficulty: 6,
    tags: ['extensions', 'jazz', 'voicing'],
    prerequisites: ['chords-sevenths-01'],
    estimateMinutes: 6,
    body: 'Extensions add colour tones above the seventh by continuing to stack thirds. A ninth is the second an octave up; an eleventh the fourth; a thirteenth the sixth. In practice, players omit some chord tones to keep voicings playable — a G13 chord might be voiced G–F–E–B (root, 7th, 13th, 3rd) without every extension sounding at once.\n\nChord symbols like Cmaj9, Dm11, or G13 tell you which extensions belong to the harmony. Major chords often take major 9ths; dominant chords accept altered tensions (♭9, ♯11) in jazz but rarely in trad backup. Extensions clarify colour when the bass and melody already state the core function.\n\nFor folk musicians exploring jazz-adjacent arranging, add extensions one at a time: try a maj7 before maj9, or a plain 7 before 9. Listen for whether the added tone supports the melody or fights it. Space and register matter more than spelling every extension on paper.',
    tryThis: '',
    quizzes: [
      {
        id: 'chords-extensions-01-q1',
        type: 'mcq',
        prompt: 'A chord labeled “maj9” includes which interval above the root (in addition to the major 7th)?',
        difficulty: 6,
        choices: [
          { id: 'a', text: 'Major ninth (compound major second)', correct: true },
          { id: 'b', text: 'Minor ninth only' },
          { id: 'c', text: 'Perfect eleventh without a seventh' },
          { id: 'd', text: 'Augmented fourth only' },
        ],
        explain: 'The 9 in maj9 indicates a major ninth above the root — the major second displaced by an octave — stacked above the maj7 chord.',
      },
      {
        id: 'chords-extensions-01-q2',
        type: 'truefalse',
        prompt: 'In real-world voicings, players often omit some chord tones when adding extensions.',
        difficulty: 6,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Practical voicings on guitar and piano frequently drop the fifth or even root, keeping guide tones and selected extensions within hand span.',
      },
    ],
  },
  {
    id: 'chords-jazz-color-01',
    title: 'Altered Dominants and Jazz Colour Chords',
    track: 'chords',
    kind: 'theory_lesson',
    difficulty: 8,
    tags: ['jazz', 'altered', 'dominant'],
    prerequisites: ['chords-extensions-01', 'chords-sevenths-01'],
    estimateMinutes: 7,
    body: 'Altered dominant chords intensify the pull toward a target by sharpening or flattening extensions on a V7 chord. G7(♭9) or G7(♯5) heighten tension before resolving to C major or C minor. The altered scale (also called super locrian) matches many of these tensions and is a staple of jazz improvisation.\n\nTritone substitution replaces V7 with a dominant chord a tritone away (Db7 for G7) because the two chords share the same guide tones (F and B/Cb). Secondary dominants temporarily tonicise another scale degree: A7→Dm in the key of C is V7/vi. These devices appear in jazz standards and in modern folk-jazz crossover arranging.\n\nTrad players need not master every altered voicing, but recognising when a chart asks for G7♯9 versus plain G7 prevents wrong notes in fusion settings. When in doubt, play the third and seventh clearly and let the soloist supply altered tensions.',
    tryThis: '',
    quizzes: [
      {
        id: 'chords-jazz-color-01-q1',
        type: 'mcq',
        prompt: 'Which chord is a common tritone substitution for G7 in the key of C?',
        difficulty: 8,
        choices: [
          { id: 'a', text: 'D♭7', correct: true },
          { id: 'b', text: 'D7' },
          { id: 'c', text: 'B♭7' },
          { id: 'd', text: 'A7' },
        ],
        explain: 'D♭7 is a tritone away from G7 and shares the same tritone interval (B–F), allowing it to resolve similarly to C.',
      },
      {
        id: 'chords-jazz-color-01-q2',
        type: 'mcq',
        prompt: 'An “altered dominant” typically modifies:',
        difficulty: 8,
        choices: [
          { id: 'a', text: 'The fifth and/or ninth (and related extensions) of a V7 chord', correct: true },
          { id: 'b', text: 'Only the root of a I chord' },
          { id: 'c', text: 'The third of a minor triad to major' },
          { id: 'd', text: 'The octave doubling of the bass line' },
        ],
        explain: 'Altered dominants sharpen or flatten the fifth and ninth (and sometimes other extensions) to increase harmonic tension before resolution.',
      },
    ],
  },
]
