/** Generated by scripts/lesson_plans/export_feed_from_lessons.py — do not edit by hand. */

import celtic_brittany from './examples-celtic-brittany.js'
import celtic_comparative from './examples-celtic-comparative.js'
import celtic_diaspora from './examples-celtic-diaspora.js'
import celtic_ireland from './examples-celtic-ireland.js'
import celtic_scotland from './examples-celtic-scotland.js'
import celtic_wales from './examples-celtic-wales.js'

export default Object.assign(
  {},
  celtic_brittany,
  celtic_comparative,
  celtic_diaspora,
  celtic_ireland,
  celtic_scotland,
  celtic_wales,
)
