export default [
  {
    id: 'foundations-pitch-01',
    title: 'The Staff, Clefs, and Pitch Names',
    track: 'foundations',
    kind: 'theory_lesson',
    difficulty: 0,
    tags: ['notation', 'pitch', 'clefs'],
    prerequisites: [],
    estimateMinutes: 4,
    body: 'Western music notation is written on a staff of five horizontal lines. Each line and each space between lines represents a different pitch. Notes can also sit above or below the staff, connected by ledger lines when they fall outside the five-line frame.\n\nThe treble clef (G clef) wraps around the second line from the bottom, marking that line as G above middle C. It is the standard clef for fiddle, flute, whistle, and most melody lines in tune books. The bass clef (F clef) places F below middle C on the fourth line and is common for piano left hand, cello, and accordion bass. Middle C sits on a ledger line between the two staves when they are joined in piano or harp notation.\n\nPitch names repeat in cycles of A through G. On the treble staff, the spaces spell F-A-C-E from bottom to top, and the lines are E-G-B-D-F. Learning one clef well is enough to start reading tunes; many trad players begin with treble and pick up bass later if they play piano or accompaniment.',
    tryThis: '',
    quizzes: [
      {
        id: 'foundations-pitch-01-q1',
        type: 'mcq',
        prompt: 'Which clef is most commonly used for fiddle and whistle melody lines in tune books?',
        difficulty: 0,
        choices: [
          { id: 'a', text: 'Treble clef (G clef)', correct: true },
          { id: 'b', text: 'Bass clef (F clef)' },
          { id: 'c', text: 'Alto clef (C clef on middle line)' },
          { id: 'd', text: 'Percussion clef' },
        ],
        explain: 'Treble clef is the standard for high-pitched melody instruments and appears in most ABC and printed tune collections.',
      },
      {
        id: 'foundations-pitch-01-q2',
        type: 'truefalse',
        prompt: 'Middle C can appear on a ledger line between treble and bass staves in piano notation.',
        difficulty: 0,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'In grand staff notation, middle C sits on a ledger line between the treble and bass staves, linking the two clefs.',
      },
    ],
  },
  {
    id: 'foundations-rhythm-01',
    title: 'Note Durations and Time Signatures',
    track: 'foundations',
    kind: 'theory_lesson',
    difficulty: 0,
    tags: ['rhythm', 'meter', 'notation'],
    prerequisites: [],
    estimateMinutes: 4,
    body: 'Rhythm tells you how long each note lasts relative to the beat. A whole note is the longest common value; a half note lasts half as long; a quarter note half again; and eighth notes move twice as fast as quarters. In ABC notation you will see these as note lengths after the letter: L:1/8 sets the default unit, and a2 means a note twice that length.\n\nThe time signature appears at the start of a tune and tells you how beats group into measures. 4/4 (common time) means four quarter-note beats per bar. 6/8 groups beats in two, each beat subdivided into three eighth notes — the feel of a jig. 2/4 and 2/2 (cut time) drive reels and many hornpipes with a steady two-beat pulse. 3/4 carries waltzes with three beats per bar.\n\nThe tempo marking (often in Italian) suggests speed, but the time signature defines the rhythmic grid. When you tap your foot to a reel, you are feeling the beat structure; when you count “ONE-and TWO-and” in a jig, you are feeling compound meter. Matching foot-tap to written meter makes sight-reading sessions far less mysterious.',
    tryThis: '',
    quizzes: [
      {
        id: 'foundations-rhythm-01-q1',
        type: 'mcq',
        prompt: 'What does a 6/8 time signature most strongly suggest about the feel of a tune?',
        difficulty: 0,
        choices: [
          { id: 'a', text: 'Two beats per bar, each divided into three eighth notes (jig feel)', correct: true },
          { id: 'b', text: 'Six equal beats per bar, all stressed equally' },
          { id: 'c', text: 'Three quarter-note beats per bar (waltz feel)' },
          { id: 'd', text: 'Four beats per bar with a backbeat on two and four' },
        ],
        explain: '6/8 is compound duple meter: two main beats per bar, each subdivided into three eighth notes, giving the lilt of a jig.',
      },
      {
        id: 'foundations-rhythm-01-q2',
        type: 'mcq',
        prompt: 'In 4/4 time, how many quarter-note beats are in one full bar?',
        difficulty: 0,
        choices: [
          { id: 'a', text: '4', correct: true },
          { id: 'b', text: '2' },
          { id: 'c', text: '3' },
          { id: 'd', text: '8' },
        ],
        explain: 'The top number of a simple time signature tells you how many beats of the given note value fit in one measure. 4/4 has four quarter-note beats.',
      },
    ],
  },
  {
    id: 'foundations-accidentals-01',
    title: 'Sharps, Flats, and Accidentals',
    track: 'foundations',
    kind: 'theory_lesson',
    difficulty: 1,
    tags: ['accidentals', 'pitch', 'keys'],
    prerequisites: ['foundations-pitch-01'],
    estimateMinutes: 4,
    body: 'Accidentals raise or lower a pitch by a half step (semitone). A sharp (♯) raises a note; a flat (♭) lowers it; a natural (♮) cancels a previous sharp or flat for that note in the measure. On fretted instruments one fret equals one semitone, which makes accidentals easy to feel under your fingers.\n\nThe key signature at the start of a tune places sharps or flats on specific lines or spaces, and they apply to every occurrence of those letter names unless overridden by an accidental in the measure. F♯ in the key signature means every F in the tune is sharp unless marked otherwise. This is why D major and G major feel different on the same melody: the collection of available pitches changes.\n\nAccidentals that appear mid-measure usually apply only until the end of that bar. Chromatic passing tones — notes that slide between scale degrees — are common in ornamented trad playing even when they are not written down. Reading key signatures accurately saves you from guessing whether a note is natural or altered.',
    tryThis: '',
    quizzes: [
      {
        id: 'foundations-accidentals-01-q1',
        type: 'mcq',
        prompt: 'What effect does a sharp (♯) have on a note?',
        difficulty: 1,
        choices: [
          { id: 'a', text: 'Raises the pitch by one semitone', correct: true },
          { id: 'b', text: 'Lowers the pitch by one semitone' },
          { id: 'c', text: 'Raises the pitch by one whole tone' },
          { id: 'd', text: 'Cancels a previous accidental' },
        ],
        explain: 'A sharp raises a pitch by one half step (semitone), the same distance as one fret on guitar or one key on a piano.',
      },
      {
        id: 'foundations-accidentals-01-q2',
        type: 'truefalse',
        prompt: 'Notes in a key signature remain altered throughout the tune unless cancelled by a natural or a new accidental.',
        difficulty: 1,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Key signature accidentals apply to every occurrence of that letter name in every octave, unless a natural sign or accidental overrides them in a measure.',
      },
    ],
  },
  {
    id: 'scales-major-01',
    title: 'Major Scales and the Leading Tone',
    track: 'foundations',
    kind: 'theory_lesson',
    difficulty: 1,
    tags: ['scales', 'major', 'leading-tone'],
    prerequisites: ['foundations-accidentals-01'],
    estimateMinutes: 5,
    body: 'A major scale follows the interval pattern whole–whole–half–whole–whole–whole–half (WWHWWWH), measured between consecutive scale degrees. From C this yields C D E F G A B C with no sharps or flats. Transpose the same pattern to G and you need F♯; start on F and you need B♭. The pattern is fixed even when the letter names change.\n\nScale degree names help you talk about melody: the first note is the tonic (home base), the fifth is the dominant (strong anchor), and the seventh is the leading tone — a half step below the tonic that strongly pulls upward to resolve. That pull is why a major tune ending on the seventh feels unfinished until you reach the tonic.\n\nFor session players, knowing the major scale in the keys you play most (G, D, A, C, and their relatives) makes transposing and harmonising by ear much faster. The WWHWWWH formula is a reliable checklist when you are unsure which notes belong in an unfamiliar key.',
    tryThis: '',
    quizzes: [
      {
        id: 'scales-major-01-q1',
        type: 'mcq',
        prompt: 'What is the interval pattern for a major scale?',
        difficulty: 1,
        choices: [
          { id: 'a', text: 'WWHWWWH', correct: true },
          { id: 'b', text: 'WHWWHWW' },
          { id: 'c', text: 'WWWHWWH' },
          { id: 'd', text: 'WHWWWHW' },
        ],
        explain: 'Major scales always follow whole–whole–half–whole–whole–whole–half between scale degrees, regardless of starting note.',
      },
      {
        id: 'scales-major-01-q2',
        type: 'mcq',
        prompt: 'In a major scale, the seventh scale degree is called the:',
        difficulty: 1,
        choices: [
          { id: 'a', text: 'Leading tone', correct: true },
          { id: 'b', text: 'Subdominant' },
          { id: 'c', text: 'Mediant' },
          { id: 'd', text: 'Supertonic' },
        ],
        explain: 'The seventh degree sits a half step below the tonic and tends to resolve upward, “leading” the ear back home.',
      },
    ],
  },
  {
    id: 'scales-minor-01',
    title: 'Natural, Harmonic, and Melodic Minor',
    track: 'foundations',
    kind: 'theory_lesson',
    difficulty: 2,
    tags: ['scales', 'minor', 'modes'],
    prerequisites: ['scales-major-01'],
    estimateMinutes: 5,
    body: 'Minor keys share the tonic–dominant relationship of major keys but use a different collection of pitches. The natural minor scale follows the pattern W-H-W-W-H-W-W from the tonic. A natural in A minor is A B C D E F G A — the relative minor of C major, using the same key signature.\n\nHarmonic minor raises the seventh degree by a half step, creating a strong leading tone (G♯ in A harmonic minor). This scale is common in classical harmony and gives minor-key cadences their characteristic pull. Melodic minor raises both the sixth and seventh degrees ascending (A B C D E F♯ G♯ A) but often reverts to natural minor descending, smoothing out awkward augmented intervals in melody.\n\nTrad tunes in minor modes (A minor, E minor, D minor) frequently mix these flavours without labelling them. A piper might lean on the raised seventh in a closing phrase while keeping the lowered sixth elsewhere. Recognising the three minor variants helps you predict which accidentals may appear in a tune and why.',
    tryThis: '',
    quizzes: [
      {
        id: 'scales-minor-01-q1',
        type: 'mcq',
        prompt: 'Which change defines harmonic minor compared to natural minor?',
        difficulty: 2,
        choices: [
          { id: 'a', text: 'The seventh degree is raised by a semitone', correct: true },
          { id: 'b', text: 'The third degree is lowered by a semitone' },
          { id: 'c', text: 'The fifth degree is raised by a semitone' },
          { id: 'd', text: 'All scale degrees are lowered' },
        ],
        explain: 'Harmonic minor raises only the seventh scale degree, creating a leading tone a half step below the tonic.',
      },
      {
        id: 'scales-minor-01-q2',
        type: 'truefalse',
        prompt: 'A natural minor has the same key signature as its relative major (three semitones higher).',
        difficulty: 2,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Relative major and minor share a key signature: A minor is relative to C major, E minor to G major, and so on.',
      },
    ],
  },
  {
    id: 'intervals-01',
    title: 'Intervals: Measuring Distance Between Notes',
    track: 'foundations',
    kind: 'theory_lesson',
    difficulty: 2,
    tags: ['intervals', 'ear-training', 'harmony'],
    prerequisites: ['scales-major-01'],
    estimateMinutes: 5,
    body: 'An interval is the distance between two pitches, named by counting letter names from the lower note to the higher (inclusive) and describing the quality (major, minor, perfect, augmented, or diminished). From C up to G is a fifth because you count C-D-E-F-G. C to E is a third; C to B is a seventh.\n\nPerfect intervals (unison, fourth, fifth, octave) have a stable, open sound. Major and minor thirds define the colour of chords: a major third sounds bright, a minor third darker. Seconds and sevenths tend to feel tense and often want to resolve. Learning to recognise thirds and fifths by ear is one of the highest-leverage skills for harmonising tunes at a session.\n\nIn ABC and printed scores, melodic intervals appear between consecutive notes; harmonic intervals sound simultaneously. Tuning matters: on fiddle, slightly narrowing major thirds compared to equal temperament is a long-standing practice. Interval names give you a shared vocabulary with other musicians when discussing harmony, transposition, and chord spelling.',
    tryThis: '',
    quizzes: [
      {
        id: 'intervals-01-q1',
        type: 'mcq',
        prompt: 'From C up to E (C–D–E) is what kind of interval?',
        difficulty: 2,
        choices: [
          { id: 'a', text: 'Major third', correct: true },
          { id: 'b', text: 'Minor third' },
          { id: 'c', text: 'Perfect fourth' },
          { id: 'd', text: 'Major second' },
        ],
        explain: 'Counting letter names C-D-E gives a third; in the major scale C to E spans two whole steps, making it a major third.',
      },
      {
        id: 'intervals-01-q2',
        type: 'mcq',
        prompt: 'Which intervals are called “perfect” in traditional Western theory?',
        difficulty: 2,
        choices: [
          { id: 'a', text: 'Unison, fourth, fifth, and octave', correct: true },
          { id: 'b', text: 'Major and minor thirds only' },
          { id: 'c', text: 'All seconds and sevenths' },
          { id: 'd', text: 'Only the octave' },
        ],
        explain: 'Perfect intervals — unison, fourth, fifth, and octave — have a characteristic stable quality distinct from major/minor thirds and sixths.',
      },
    ],
  },
  {
    id: 'keys-circle-01',
    title: 'The Circle of Fifths and Key Signatures',
    track: 'foundations',
    kind: 'theory_lesson',
    difficulty: 3,
    tags: ['keys', 'circle-of-fifths', 'signatures'],
    prerequisites: ['scales-major-01', 'foundations-accidentals-01'],
    estimateMinutes: 6,
    body: 'The circle of fifths arranges keys so each step clockwise adds one sharp. Starting at C (no sharps or flats), G major has one sharp, D major two, A major three, and so on. Moving counter-clockwise adds flats: F major has one flat, B♭ major two, E♭ major three. Keys a fifth apart share six of seven scale degrees, which is why modulations often move by fifths.\n\nThe order of sharps in key signatures is F♯ C♯ G♯ D♯ A♯ E♯ B♯ — remembered by the mnemonic “Father Charles Goes Down And Ends Battle.” Flats appear in the reverse order: B♭ E♭ A♭ D♭ G♭ C♭ F♭ (“Battle Ends And Down Goes Charles’ Father”). The last sharp in a key signature tells you the major key: for sharps, go up a half step from that sharp; for flats, the second-to-last flat names the major key.\n\nFor trad musicians, the sharp-side keys G, D, A, and E dominate fiddle and whistle repertoire, while B♭ and F appear often on flute and box. Mapping tunes onto the circle reveals friendly modulations and helps you prepare accidentals before the first downbeat.',
    tryThis: '',
    quizzes: [
      {
        id: 'keys-circle-01-q1',
        type: 'mcq',
        prompt: 'What is the correct order of sharps added in key signatures?',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'F♯ C♯ G♯ D♯ A♯ E♯ B♯', correct: true },
          { id: 'b', text: 'G♯ D♯ A♯ E♯ B♯ F♯ C♯' },
          { id: 'c', text: 'C♯ G♯ D♯ A♯ E♯ B♯ F♯' },
          { id: 'd', text: 'F♯ G♯ A♯ B♯ C♯ D♯ E♯' },
        ],
        explain: 'Sharps always enter key signatures in the fixed order F-C-G-D-A-E-B, moving by fifths.',
      },
      {
        id: 'keys-circle-01-q2',
        type: 'mcq',
        prompt: 'How many sharps are in the key of D major?',
        difficulty: 3,
        choices: [
          { id: 'a', text: '2 (F♯ and C♯)', correct: true },
          { id: 'b', text: '1 (F♯ only)' },
          { id: 'c', text: '3 (F♯, C♯, and G♯)' },
          { id: 'd', text: 'None' },
        ],
        explain: 'D major is two steps clockwise from C on the circle of fifths, so it carries F♯ and C♯ in its key signature.',
      },
    ],
  },
]
