export default [
  {
    id: 'harmony-tendency-01',
    title: 'Tendency Tones and Resolution',
    track: 'harmony',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['tendency', 'resolution', 'voice-leading'],
    prerequisites: ['chords-diatonic-major-01'],
    estimateMinutes: 5,
    body: 'Certain pitches in a key “want” to move to others. The leading tone (seventh scale degree in major) rises to the tonic. The fourth degree in a V chord often falls to the third of I. These tendency tones create the feeling of arrival when a phrase ends.\n\nDominant harmony concentrates tension: the tritone between the third and seventh of V7 (B and F in G7→C) resolves outward to C and E. Melodic tendency works too: a phrase ending on 2̂ often steps down to 1̂ or up to 3̂ depending on style. Trad players exploit this instinctively when ornamenting cadences.\n\nBacking musicians who land on chord tones that clash with unresolved melody tendency can sound “wrong” even when the chord is diatonic. Listening for where the melody wants to go helps you choose inversions and passing chords that support rather than block the line.',
    tryThis: '',
    quizzes: [
      {
        id: 'harmony-tendency-01-q1',
        type: 'mcq',
        prompt: 'In major keys, the leading tone most strongly resolves:',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'Up to the tonic (by semitone)', correct: true },
          { id: 'b', text: 'Down to the subdominant' },
          { id: 'c', text: 'Up to the mediant by whole tone' },
          { id: 'd', text: 'It has no preferred direction' },
        ],
        explain: 'The leading tone sits a half step below the tonic and conventionally rises to complete the cadence.',
      },
      {
        id: 'harmony-tendency-01-q2',
        type: 'truefalse',
        prompt: 'The tritone in a dominant seventh chord creates tension that typically resolves in a cadence.',
        difficulty: 4,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'The augmented fourth/diminished fifth inside V7 resolves to stable chord tones of I, defining the dominant function.',
      },
    ],
  },
  {
    id: 'harmony-voiceleading-01',
    title: 'Voice Leading Basics',
    track: 'harmony',
    kind: 'theory_lesson',
    difficulty: 5,
    tags: ['voice-leading', 'part-writing', 'smoothness'],
    prerequisites: ['harmony-tendency-01', 'chords-inversions-01'],
    estimateMinutes: 6,
    body: 'Voice leading describes how individual parts move from chord to chord. Smooth voice leading favours small steps, common tones held between chords, and contrary motion between outer voices. Large leaps in inner voices are fine on fiddle; in four-part harmony they can sound disjointed unless prepared.\n\nParallel perfect fifths and octaves between independent voices were avoided in classical part-writing because they weaken independence of lines. In trad ensemble playing the “voices” might be fiddle, flute, and guitar — doubling the melody in octaves is normal, but two harmony instruments moving in parallel fifths throughout can hollow out the texture.\n\nPractical session voice leading: keep the bass moving by step or fifth when possible; let harmony instruments stick to chord tones on strong beats; add passing motion on weak beats. When arranging a three-part hornpipe set, assign one player roots, another thirds, another fifths or melody doubles — clarity beats cleverness.',
    tryThis: '',
    quizzes: [
      {
        id: 'harmony-voiceleading-01-q1',
        type: 'mcq',
        prompt: 'Smooth voice leading generally prefers:',
        difficulty: 5,
        choices: [
          { id: 'a', text: 'Small melodic steps and retaining common tones between chords', correct: true },
          { id: 'b', text: 'Large leaps in every voice on every change' },
          { id: 'c', text: 'All voices moving in parallel octaves always' },
          { id: 'd', text: 'Random chord tones with no regard for spacing' },
        ],
        explain: 'Stepwise motion and shared notes connect harmonies and keep independent lines intelligible.',
      },
      {
        id: 'harmony-voiceleading-01-q2',
        type: 'mcq',
        prompt: 'Contrary motion means:',
        difficulty: 5,
        choices: [
          { id: 'a', text: 'One voice rises while another falls', correct: true },
          { id: 'b', text: 'All voices move in the same direction' },
          { id: 'c', text: 'Only the bass may move' },
          { id: 'd', text: 'Voices must repeat the same pitch' },
        ],
        explain: 'Contrary motion between outer voices (soprano and bass) helps maintain balance and independence in texture.',
      },
    ],
  },
  {
    id: 'harmony-cadences-01',
    title: 'Cadences: Full, Half, Plagal, and Deceptive',
    track: 'harmony',
    kind: 'theory_lesson',
    difficulty: 5,
    tags: ['cadences', 'phrasing', 'harmony'],
    prerequisites: ['harmony-tendency-01'],
    estimateMinutes: 5,
    body: 'A cadence is a harmonic punctuation mark at a phrase end. An authentic (full) cadence moves V→I (or V7→I) and feels like a firm full stop — common at the end of a tune part. A half cadence lands on V and feels like a comma or question, often at the midpoint of a strain before the repeat.\n\nA plagal cadence (IV→I, the “amen” cadence) softens an ending after the dominant has already appeared. A deceptive cadence moves V→vi instead of V→I, surprising the ear — less common in straight dance tunes but useful in songs and airs. Recognising cadence types helps you breathe and bow with the architecture of the melody.\n\nIn AABB tunes, the A part often half-cadences before the repeat while the B part authentic-cadences home. Accompanists who push dominant harmony too early can steal the half cadence’s lift. Mark cadence points when learning a new reel and your phrasing will match experienced session players faster.',
    tryThis: '',
    quizzes: [
      {
        id: 'harmony-cadences-01-q1',
        type: 'mcq',
        prompt: 'A V→I progression at a phrase end is called:',
        difficulty: 5,
        choices: [
          { id: 'a', text: 'An authentic (full) cadence', correct: true },
          { id: 'b', text: 'A half cadence' },
          { id: 'c', text: 'A deceptive cadence' },
          { id: 'd', text: 'A plagal cadence only' },
        ],
        explain: 'Dominant to tonic (V→I) is the classic authentic cadence, providing strong closure.',
      },
      {
        id: 'harmony-cadences-01-q2',
        type: 'mcq',
        prompt: 'A half cadence typically ends on which chord?',
        difficulty: 5,
        choices: [
          { id: 'a', text: 'V (dominant)', correct: true },
          { id: 'b', text: 'I (tonic)' },
          { id: 'c', text: 'vi (submediant)' },
          { id: 'd', text: 'iv (subdominant) only in minor' },
        ],
        explain: 'Half cadences pause on the dominant, creating expectation without full resolution to tonic.',
      },
    ],
  },
  {
    id: 'harmony-phrases-01',
    title: 'Phrase Structure in Tunes and Songs',
    track: 'harmony',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['phrasing', 'form', 'analysis'],
    prerequisites: ['harmony-cadences-01'],
    estimateMinutes: 5,
    body: 'Musical phrases are coherent chunks of melody, often four or eight bars, ending with a cadence. Irish dance tunes frequently use two-bar cells grouped into eight-bar parts. Songs may use question–answer phrasing: bars 1–4 rise or open, bars 5–8 settle toward tonic.\n\nAntecedent and consequent phrases pair so the first asks and the second answers harmonically. In “The Star of the County Down,” phrase endings often alternate weaker and stronger cadences. Mapping phrases reveals where to breathe, where to add variation on the repeat, and where percussion might mark a turn.\n\nHarmonic rhythm — how often chords change — interacts with phrase length. A tune with one chord per bar feels different from one that stays on I for four bars then shifts. When arranging, align chord changes with phrase boundaries unless you deliberately syncopate against them for effect.',
    tryThis: '',
    quizzes: [
      {
        id: 'harmony-phrases-01-q1',
        type: 'mcq',
        prompt: 'An eight-bar strain in many dance tunes often divides into:',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'Two four-bar phrases', correct: true },
          { id: 'b', text: 'Eight one-bar phrases with no grouping' },
          { id: 'c', text: 'One sixteen-bar phrase' },
          { id: 'd', text: 'Three equal three-bar phrases' },
        ],
        explain: 'Four-plus-four bar grouping is standard in reels, jigs, and hornpipes, often with a cadence at the midpoint and end.',
      },
      {
        id: 'harmony-phrases-01-q2',
        type: 'truefalse',
        prompt: 'Phrase endings often coincide with cadence points in the harmony.',
        difficulty: 4,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Melodic phrase boundaries typically align with harmonic cadences, giving listeners a sense of punctuation.',
      },
    ],
  },
  {
    id: 'harmony-secondary-01',
    title: 'Secondary Dominants and Tonicisation',
    track: 'harmony',
    kind: 'theory_lesson',
    difficulty: 7,
    tags: ['secondary-dominants', 'tonicisation', 'harmony'],
    prerequisites: ['chords-sevenths-01', 'harmony-cadences-01'],
    estimateMinutes: 6,
    body: 'A secondary dominant temporarily treats a non-tonic chord as a local key centre. In C major, A7 is V7/vi because it resolves to Dm (vi). D7 is V7/V, pulling to G. These chords introduce accidentals not in the home key signature — A7 brings C♯ into C major.\n\nSecondary dominants add directional colour in songs and arranged trad medleys without full modulation. You might hear V7/vi→vi as a brief brightening before returning to I. They appear in O’Carolan arrangements, ragtime-influenced hornpipes, and contemporary folk songwriting.\n\nLabel secondary dominants by the chord they target: “five of six” means dominant seventh on the note a fifth above the vi root. If the melody suddenly sharpens a note outside the key signature for one bar, suspect a secondary dominant or modal mixture rather than a full key change.',
    tryThis: '',
    quizzes: [
      {
        id: 'harmony-secondary-01-q1',
        type: 'mcq',
        prompt: 'In C major, which chord functions as V7/vi (dominant of vi)?',
        difficulty: 7,
        choices: [
          { id: 'a', text: 'A7', correct: true },
          { id: 'b', text: 'E7' },
          { id: 'c', text: 'G7' },
          { id: 'd', text: 'F7' },
        ],
        explain: 'vi in C is Dm; the dominant a fifth above D is A, so A7 tonicises D minor before resolving.',
      },
      {
        id: 'harmony-secondary-01-q2',
        type: 'mcq',
        prompt: 'Secondary dominants typically introduce:',
        difficulty: 7,
        choices: [
          { id: 'a', text: 'Accidentals foreign to the home key signature', correct: true },
          { id: 'b', text: 'Only notes from the home major scale' },
          { id: 'c', text: 'Silence between sections' },
          { id: 'd', text: 'A change of time signature' },
        ],
        explain: 'To act as V7 of a target chord, the secondary dominant often needs a raised third (and other tendency tones) outside the home key.',
      },
    ],
  },
  {
    id: 'harmony-modulation-01',
    title: 'Modulation: Changing Key Mid-Tune',
    track: 'harmony',
    kind: 'theory_lesson',
    difficulty: 8,
    tags: ['modulation', 'keys', 'advanced'],
    prerequisites: ['harmony-secondary-01', 'keys-circle-01'],
    estimateMinutes: 7,
    body: 'Modulation means establishing a new tonic, not merely touching foreign chords. Common moves include up a whole step (G→A) for energy, to the relative minor (G→Em), or by common chord (pivot) shared by two keys — C major serves as IV in G and I in C.\n\nDirect modulation jumps without preparation, often at a section break in arranged sets. Chromatic modulation uses a voice chromatically altered to slip into a new key. In trad, full modulations are less common in core repertoire than in céilí band arrangements or song verses, but key changes appear in medleys and competition sets.\n\nDetect modulation by sustained new accidentals and cadences confirming a new tonic. A single A7 in D major is tonicisation; four bars solidly in A with cadence to A is modulation. Accompanists should agree on whether a B part modulates or merely borrows chords before the repeat.',
    tryThis: '',
    quizzes: [
      {
        id: 'harmony-modulation-01-q1',
        type: 'mcq',
        prompt: 'A pivot-chord modulation uses:',
        difficulty: 8,
        choices: [
          { id: 'a', text: 'A chord that belongs to both the old and new keys as a bridge', correct: true },
          { id: 'b', text: 'Only silence between keys' },
          { id: 'c', text: 'A tempo change without harmonic change' },
          { id: 'd', text: 'Random accidentals with no cadence' },
        ],
        explain: 'A common chord is reinterpreted in the new key (e.g., G major as V in C and I in G) to smooth the transition.',
      },
      {
        id: 'harmony-modulation-01-q2',
        type: 'truefalse',
        prompt: 'Modulation establishes a new tonic, whereas tonicisation is a brief visit without full key change.',
        difficulty: 8,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Tonicisation highlights a chord temporarily via secondary dominants; modulation settles into a new key centre.',
      },
    ],
  },
  {
    id: 'harmony-counterpoint-01',
    title: 'Counterpoint: Independent Melodic Lines',
    track: 'harmony',
    kind: 'theory_lesson',
    difficulty: 9,
    tags: ['counterpoint', 'polyphony', 'advanced'],
    prerequisites: ['harmony-voiceleading-01'],
    estimateMinutes: 7,
    body: 'Counterpoint is the art of combining melodies so each line remains musically intelligible while harmonising together. Species counterpoint (Gradus ad Parnassum tradition) trains stepwise motion, consonance on strong beats, and careful treatment of dissonance — skills that underpin Bach fugues and also inform twin-fiddle harmony.\n\nContrary and oblique motion between lines maintain independence; excessive parallel motion makes lines blur. In Irish trad, counterpoint appears in pipe regulators, harp bass lines, and twin-fiddle arrangements where the second player weaves a countermelody below the tune. The lines need not move in rhythmic unison; off-beat counter figures add lift.\n\nStrict academic rules relax in oral tradition, but the ear still prefers consonant intervals on downbeats and clear resolution of dissonance. When writing a harmony part, sing both lines separately: if either sounds like random notes, simplify until each stands alone.',
    tryThis: '',
    quizzes: [
      {
        id: 'harmony-counterpoint-01-q1',
        type: 'mcq',
        prompt: 'The main goal of counterpoint is:',
        difficulty: 9,
        choices: [
          { id: 'a', text: 'Combine independent melodic lines that remain coherent individually', correct: true },
          { id: 'b', text: 'Play the same melody in unison always' },
          { id: 'c', text: 'Eliminate all dissonance on every beat' },
          { id: 'd', text: 'Replace harmony with percussion only' },
        ],
        explain: 'Counterpoint balances horizontal melody writing with vertical consonance, keeping each voice musically meaningful.',
      },
      {
        id: 'harmony-counterpoint-01-q2',
        type: 'mcq',
        prompt: 'Contrary motion in two-part writing means:',
        difficulty: 9,
        choices: [
          { id: 'a', text: 'One line ascends while the other descends', correct: true },
          { id: 'b', text: 'Both lines use identical rhythm and direction always' },
          { id: 'c', text: 'Only one line may contain notes' },
          { id: 'd', text: 'Both lines must end on the same pitch' },
        ],
        explain: 'Contrary motion preserves independence between voices and is a cornerstone of classical counterpoint technique.',
      },
    ],
  },
]
