export default [
  {
    id: 'history-bach-01',
    title: 'J.S. Bach: Counterpoint and Dance Forms',
    track: 'history',
    kind: 'theory_lesson',
    difficulty: 3,
    tags: ['bach', 'baroque', 'history'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Johann Sebastian Bach (1685–1750) worked in German churches and courts, composing fugues, chorales, suites, and partitas that remain central to Western music education. His Well-Tempered Clavier demonstrated that keyboard music could move through all major and minor keys — a direct ancestor of how we think about the circle of fifths today.\n\nBach absorbed dance rhythms — allemandes, gigues, minuets — into instrumental suites. Trad musicians care about Bach because his part-writing clarifies how independent lines fit together, skills transferable to twin-fiddle harmony or pipe regulator accompaniment. His ornament tables also influenced how baroque-influenced harp and classical flute players approach gracing.\n\nYou need not play Bach to benefit from him: studying one two-part invention shows how a bass line can imply harmony while the right hand sings melody — the same split session guitarists and pianists use behind a tune.',
    tryThis: '',
    quizzes: [
      {
        id: 'history-bach-01-q1',
        type: 'mcq',
        prompt: 'Bach’s Well-Tempered Clavier is especially famous for:',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'Preludes and fugues in all major and minor keys', correct: true },
          { id: 'b', text: 'Inventing the tin whistle' },
          { id: 'c', text: 'Writing only jazz standards' },
          { id: 'd', text: 'Composing exclusively for electric guitar' },
        ],
        explain: 'The 48 preludes and fugues cycle through the keys, a landmark of baroque keyboard craft and equal-temperament thinking.',
      },
      {
        id: 'history-bach-01-q2',
        type: 'truefalse',
        prompt: 'Bach incorporated dance forms such as gigues into his instrumental suites.',
        difficulty: 3,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Baroque suites commonly ended with gigues and included other court dances, linking Bach to the broader European dance tradition.',
      },
    ],
  },
  {
    id: 'history-mozart-01',
    title: 'Mozart: Clarity, Balance, and Melody',
    track: 'history',
    kind: 'theory_lesson',
    difficulty: 3,
    tags: ['mozart', 'classical', 'history'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Wolfgang Amadeus Mozart (1756–1791) wrote symphonies, operas, chamber music, and piano works with effortless melodic balance. Classical-era ideals — clear phrases, balanced antecedent/consequent structure, and transparent harmony — appear throughout his music and still shape how we hear “well-formed” tunes.\n\nFolk musicians encounter Mozart through classical flute repertoire, string quartet arrangements of trad tunes, and the idea that a melody should breathe in even four-bar units. His piano sonatas illustrate Alberti bass patterns and simple I–V–I harmonic motion that underpin countless songs.\n\nMozart matters practically because his phrasing model helps you shape airs and slow sessions tunes: lift at the midpoint cadence, settle at the authentic cadence, and keep inner rhythm steady even when ornamenting.',
    tryThis: '',
    quizzes: [
      {
        id: 'history-mozart-01-q1',
        type: 'mcq',
        prompt: 'Mozart is associated with which broad musical era?',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'Classical era', correct: true },
          { id: 'b', text: 'Baroque era only' },
          { id: 'c', text: '20th-century serialism' },
          { id: 'd', text: 'Electric blues' },
        ],
        explain: 'Mozart’s career sits in the late Classical period, between Baroque complexity and Romantic expressiveness.',
      },
      {
        id: 'history-mozart-01-q2',
        type: 'mcq',
        prompt: 'Why might a trad player study Mozart’s phrasing?',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'His clear four-bar phrases model breathing and cadence points', correct: true },
          { id: 'b', text: 'He invented the uilleann pipes' },
          { id: 'c', text: 'He wrote only in 7/8 time' },
          { id: 'd', text: 'He rejected all dance rhythms' },
        ],
        explain: 'Classical phrase symmetry helps musicians shape slow airs and songs with intentional cadences and balanced lines.',
      },
    ],
  },
  {
    id: 'history-beethoven-01',
    title: 'Beethoven: Drama, Form, and Expansion',
    track: 'history',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['beethoven', 'romantic', 'history'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Ludwig van Beethoven (1770–1827) bridged Classical and Romantic styles, expanding form and emotional range in symphonies, sonatas, and string quartets. He stretched development sections, intensified dynamic contrasts, and made motivic cells — short rhythmic or melodic ideas — drive entire movements.\n\nTrad players feel Beethoven’s influence when arrangements add dramatic key changes, sudden dynamic shifts, or developmental variation on a repeated tune part. His emphasis on rhythmic motive (think of the Fifth Symphony opening) parallels how reel pick-up notes and rhythmic drive define dance music.\n\nBeethoven also championed music as personal expression rather than pure court entertainment. That ethos echoes in folk revival movements where community musicians claim ownership of repertoire, not only virtuoso elites.',
    tryThis: '',
    quizzes: [
      {
        id: 'history-beethoven-01-q1',
        type: 'mcq',
        prompt: 'Beethoven is often described as bridging which two stylistic periods?',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'Classical and Romantic', correct: true },
          { id: 'b', text: 'Medieval and Renaissance' },
          { id: 'c', text: 'Baroque and jazz' },
          { id: 'd', text: 'Minimalism and hip-hop' },
        ],
        explain: 'Beethoven’s early works follow Classical models; his later works expand form and expression toward Romantic ideals.',
      },
      {
        id: 'history-beethoven-01-q2',
        type: 'truefalse',
        prompt: 'Beethoven frequently built large forms from small recurring motives.',
        difficulty: 4,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Motivic development — spinning entire movements from brief ideas — is a hallmark of Beethoven’s compositional method.',
      },
    ],
  },
  {
    id: 'history-chopin-01',
    title: 'Chopin: Piano Colour and Rubato',
    track: 'history',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['chopin', 'piano', 'history'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Frédéric Chopin (1810–1849) composed almost exclusively for piano, creating nocturnes, mazurkas, polonaises, and études that redefine touch and colour at the instrument. His music privileges singing right-hand lines over harmonic accompaniment patterns in the left hand — a texture folk pianists mimic when backing slow airs.\n\nChopin’s use of rubato — flexible timing within a steady pulse — connects to oral-tradition phrasing where melody breathes while rhythm section holds tempo. His mazurkas also show how national dance rhythms (Polish triple meter with accent shifts) can live inside concert music, much as Irish dances live inside both kitchen sessions and staged recitals.\n\nEven non-classical players gain from Chopin: voicing chords so melody floats above, pedalling sparingly in dance halls, and treating ornaments as expressive rather than mechanical.',
    tryThis: '',
    quizzes: [
      {
        id: 'history-chopin-01-q1',
        type: 'mcq',
        prompt: 'Chopin is most closely associated with which instrument?',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'Piano', correct: true },
          { id: 'b', text: 'Bagpipes' },
          { id: 'c', text: 'Electric bass' },
          { id: 'd', text: 'Synthesizer' },
        ],
        explain: 'Chopin’s catalogue is overwhelmingly piano music, shaping Romantic keyboard technique and expression.',
      },
      {
        id: 'history-chopin-01-q2',
        type: 'mcq',
        prompt: 'Rubato in Chopin’s tradition generally means:',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'Flexible timing in the melody while overall pulse remains', correct: true },
          { id: 'b', text: 'Playing as fast as possible' },
          { id: 'c', text: 'Ignoring harmony entirely' },
          { id: 'd', text: 'Strict metronomic equality on every note' },
        ],
        explain: 'Rubato stretches and releases melodic time expressively without losing the underlying rhythmic framework.',
      },
    ],
  },
  {
    id: 'history-debussy-01',
    title: 'Debussy: Colour, Modes, and New Sonorities',
    track: 'history',
    kind: 'theory_lesson',
    difficulty: 5,
    tags: ['debussy', 'impressionism', 'history'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Claude Debussy (1862–1918) broke from functional Germanic harmony toward colour, parallel motion, and modal scales. Pieces like “Prélude à l’après-midi d’un faune” treat chords as sonorities rather than strict voice-leading targets, influencing film music and contemporary folk arranging.\n\nDebussy drew on whole-tone and pentatonic collections that feel familiar to players of Celtic and Asian-influenced tunes. His avoidance of heavy dominant-tonic cadences parallels modal Irish melodies that centre on a pitch without constant V–I motion. Harp and piano players arranging airs borrow Debussy’s voicing spacing — wide gaps, soft doublings — for atmospheric intros.\n\nUnderstanding Debussy helps when a tune “floats” harmonically: you may colour with parallel triads or planing chords instead of forcing classical cadences where the melody never asked for them.',
    tryThis: '',
    quizzes: [
      {
        id: 'history-debussy-01-q1',
        type: 'mcq',
        prompt: 'Debussy’s harmony is often described as favouring:',
        difficulty: 5,
        choices: [
          { id: 'a', text: 'Colour and sonority over strict functional progression', correct: true },
          { id: 'b', text: 'Strict Bach-style fugues exclusively' },
          { id: 'c', text: 'Only twelve-tone serial rows' },
          { id: 'd', text: 'Unison brass band scoring only' },
        ],
        explain: 'Impressionist harmony emphasises timbre and modal colour rather than relentless dominant-tonic drive.',
      },
      {
        id: 'history-debussy-01-q2',
        type: 'truefalse',
        prompt: 'Whole-tone and pentatonic scales appear in Debussy’s language and also in many folk traditions.',
        difficulty: 5,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Debussy’s scales overlap with folk and non-Western collections, blurring the line between art music and oral tradition.',
      },
    ],
  },
  {
    id: 'history-armstrong-01',
    title: 'Louis Armstrong: Swing, Phrasing, and Improvisation',
    track: 'history',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['armstrong', 'jazz', 'history'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Louis Armstrong (1901–1971) transformed jazz from collective New Orleans polyphony into virtuoso solo trumpet and vocal phrasing. His recordings in the 1920s with the Hot Five and Hot Seven set templates for swing rhythm, blues inflection, and improvising on chord changes.\n\nFolk musicians hear Armstrong’s legacy in swung hornpipes, jazz-waltz sessions, and any tune where the melody player “plays behind the beat” then catches up. His vocal scat lines treat pitch and rhythm as equal expressive tools — not unlike sean-nós or Appalachian ornament that bends time.\n\nArmstrong also modelled storytelling in a single chorus: start simple, build intensity, land a memorable ending. That arc applies to variation on the repeat in Irish dance music, even without jazz harmony.',
    tryThis: '',
    quizzes: [
      {
        id: 'history-armstrong-01-q1',
        type: 'mcq',
        prompt: 'Louis Armstrong was a pioneering virtuoso on:',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'Trumpet (and voice)', correct: true },
          { id: 'b', text: 'Harpsichord' },
          { id: 'c', text: 'Uilleann pipes' },
          { id: 'd', text: 'Sitar' },
        ],
        explain: 'Armstrong’s trumpet solos and gravelly vocals defined early jazz solo style and swing phrasing.',
      },
      {
        id: 'history-armstrong-01-q2',
        type: 'mcq',
        prompt: '“Swing” in Armstrong’s era refers to:',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'A rhythmic feel that subdivides the beat with bounce and syncopation', correct: true },
          { id: 'b', text: 'Playing exactly on the metronome with no deviation' },
          { id: 'c', text: 'A type of classical opera' },
          { id: 'd', text: 'Only 6/8 jig rhythm' },
        ],
        explain: 'Swing places emphasis flexibly within the beat, creating the propulsive lilt central to jazz and related folk fusion.',
      },
    ],
  },
  {
    id: 'history-ellington-01',
    title: 'Duke Ellington: Band Colour and Composition',
    track: 'history',
    kind: 'theory_lesson',
    difficulty: 5,
    tags: ['ellington', 'jazz', 'history'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Duke Ellington (1899–1974) led one of the greatest big bands, composing thousands of pieces that treat each section — reeds, brass, rhythm — as a palette of colour. “Mood Indigo,” “Take the A Train,” and extended suites show how arrangement equals composition.\n\nTrad musicians benefit from Ellington’s lesson that harmony is orchestration: the same chord voiced differently changes the room. Céilí bands and folk big bands borrow this when assigning countermelodies to accordion versus fiddle versus brass. Ellington also wrote for dancers, linking jazz to social dance like trad links tunes to sets.\n\nStudy Ellington when arranging medleys: vary texture each turn, give soloists space over rich backgrounds, and use shout choruses for climax — techniques transferable to festival sets.',
    tryThis: '',
    quizzes: [
      {
        id: 'history-ellington-01-q1',
        type: 'mcq',
        prompt: 'Duke Ellington is best known as a:',
        difficulty: 5,
        choices: [
          { id: 'a', text: 'Bandleader and composer of jazz orchestra music', correct: true },
          { id: 'b', text: 'Baroque organ specialist only' },
          { id: 'c', text: 'Silent-film pianist exclusively' },
          { id: 'd', text: 'Heavy-metal guitarist' },
        ],
        explain: 'Ellington’s orchestra and compositions are cornerstones of American jazz, emphasising sectional colour and arrangement.',
      },
      {
        id: 'history-ellington-01-q2',
        type: 'truefalse',
        prompt: 'Ellington treated individual band sections as distinct colours in his arrangements.',
        difficulty: 5,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Ellington wrote parts tailored to specific players and sections, making orchestration central to his sound.',
      },
    ],
  },
  {
    id: 'history-parker-01',
    title: 'Charlie Parker: Bebop and Harmonic Velocity',
    track: 'history',
    kind: 'theory_lesson',
    difficulty: 6,
    tags: ['parker', 'bebop', 'history'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Charlie “Bird” Parker (1920–1955) revolutionised jazz alto saxophone with bebop — fast harmonic rhythm, chromatic passing tones, and improvising on chord changes rather than melody alone. Tunes like “Confirmation” and “Blues for Alice” became études for jazz musicians worldwide.\n\nBebop’s chord sophistication influenced folk-jazz crossover: backing a reel with ii–V–I substitutions or altered dominants traces to Parker’s generation even when players never play jazz gigs. Bird also shows how oral tradition plus rigorous practice (hours of technique daily) produces new vocabulary within existing forms.\n\nFor trad players curious about improvisation, Parker demonstrates targeting chord tones on strong beats while using chromatic approaches between them — a method you can apply sparingly on modal tunes without full bebop velocity.',
    tryThis: '',
    quizzes: [
      {
        id: 'history-parker-01-q1',
        type: 'mcq',
        prompt: 'Charlie Parker was a central figure in which jazz style?',
        difficulty: 6,
        choices: [
          { id: 'a', text: 'Bebop', correct: true },
          { id: 'b', text: 'Dixieland only' },
          { id: 'c', text: 'Smooth jazz of the 1980s' },
          { id: 'd', text: 'Gregorian chant' },
        ],
        explain: 'Parker, with Dizzy Gillespie and others, pioneered bebop’s fast harmonic language and improvisational complexity.',
      },
      {
        id: 'history-parker-01-q2',
        type: 'mcq',
        prompt: 'Bebop improvisation typically emphasises:',
        difficulty: 6,
        choices: [
          { id: 'a', text: 'Navigating chord changes with chromatic lines', correct: true },
          { id: 'b', text: 'Playing only the written melody unchanged' },
          { id: 'c', text: 'Avoiding all seventh chords' },
          { id: 'd', text: 'Strict unison with no variation' },
        ],
        explain: 'Bebop soloists outline harmonies rapidly, using extensions and chromatic approaches between chord tones.',
      },
    ],
  },
  {
    id: 'history-trad-collectors-01',
    title: 'Collectors and Revivals: Saving Oral Tradition',
    track: 'history',
    kind: 'theory_lesson',
    difficulty: 3,
    tags: ['collectors', 'revival', 'trad'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Without field collectors, much trad repertoire would be lost. Francis O’Neill published thousands of Irish dance tunes from Chicago musicians; Cecil Sharp documented English morris and country dances; Alan Lomax and others recorded Appalachian ballads and blues. Their notebooks and 78rpm sessions became the tune books and archives we search today.\n\nCollectors did not merely transcribe — they shaped revival taste by what they chose to publish and how they harmonised melodies. Modern players owe them access but also critique sources: versions differ, titles drift, and printed keys may not match local practice.\n\nWhen you add a tune from abc2book or a PDF collection, you join a chain from kitchen player to collector to digital archive. Cite sources when possible and stay open to living players who remember alternate turns.',
    tryThis: '',
    quizzes: [
      {
        id: 'history-trad-collectors-01-q1',
        type: 'mcq',
        prompt: 'Captain Francis O’Neill is famous for:',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'Publishing large collections of Irish dance tunes', correct: true },
          { id: 'b', text: 'Inventing the piano forte' },
          { id: 'c', text: 'Writing symphonies in Vienna' },
          { id: 'd', text: 'Founding bebop in New York' },
        ],
        explain: 'O’Neill’s “Music of Ireland” and related volumes preserved thousands of tunes from Irish-American musicians.',
      },
      {
        id: 'history-trad-collectors-01-q2',
        type: 'truefalse',
        prompt: 'Field collectors helped preserve oral-tradition music that might otherwise have been lost.',
        difficulty: 3,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Transcription and recording projects created durable records of tunes passed primarily by ear in community settings.',
      },
    ],
  },
  {
    id: 'history-women-01',
    title: 'Women in Music History: Composers and Tradition Bearers',
    track: 'history',
    kind: 'theory_lesson',
    difficulty: 3,
    tags: ['women', 'history', 'trad'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Music history textbooks long underrepresented women, yet women composed, performed, collected, and carried traditions at every level. Hildegard of Bingen wrote visionary monophonic works; Clara Schumann concertised and composed; Fanny Mendelssohn’s lieder circulated under her brother’s name. In trad music, women singers and dancers often preserved repertoire in domestic settings while public stages were restricted.\n\nContemporary players benefit from recovering these voices: harpist composers like Turlough O’Carolan sit beside lesser-known women tune-writers and song carriers documented in regional archives. Festivals now highlight women pipers, fiddlers, and accordionists who were always in sessions but rarely featured on album covers.\n\nSeeking diverse sources improves your repertoire and your ensemble culture. When arranging historical music, ask who is missing from the printed page — the answer often leads to richer sets and fairer credit.',
    tryThis: '',
    quizzes: [
      {
        id: 'history-women-01-q1',
        type: 'mcq',
        prompt: 'Clara Schumann was known primarily as a:',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'Pianist and composer', correct: true },
          { id: 'b', text: 'Baroque trumpet maker' },
          { id: 'c', text: 'Disc jockey' },
          { id: 'd', text: 'Silent-film projectionist' },
        ],
        explain: 'Clara Schumann was a leading 19th-century pianist who also composed songs and chamber works.',
      },
      {
        id: 'history-women-01-q2',
        type: 'truefalse',
        prompt: 'Women have historically participated in carrying oral-tradition music even when underrepresented in published collections.',
        difficulty: 3,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Domestic and community settings often relied on women singers and musicians whose contributions were less documented than male public performers.',
      },
    ],
  },
]
