export default [
  {
    id: 'italian-tempo-01',
    title: 'Italian Tempo Markings',
    track: 'italian',
    kind: 'theory_lesson',
    difficulty: 1,
    tags: ['tempo', 'italian', 'performance'],
    prerequisites: [],
    estimateMinutes: 4,
    body: 'Italian tempo markings appear on printed scores and in tune collections to suggest how fast a piece should feel. They describe character as much as speed: Allegro means lively and fast, Andante means walking pace, Adagio means slow and stately, and Presto means very fast. Moderato sits in the middle — neither rushed nor dragging.\n\nMany markings modify a base tempo. Allegretto is a little slower than allegro; Andantino can be slightly faster than andante depending on period and editor. Largo and Lento both indicate slow tempi, but largo often implies broad, open phrases. Vivace adds sparkle and energy beyond mere speed.\n\nIn trad sessions tempo is usually negotiated by the leader’s first phrase rather than a printed marking, but these terms still appear on classical arrangements, céilí band charts, and written-out sets. Recognising them helps you interpret recordings and printed versions of tunes that were originally passed down by ear.',
    tryThis: '',
    quizzes: [
      {
        id: 'italian-tempo-01-q1',
        type: 'mcq',
        prompt: 'Which tempo marking suggests a walking pace?',
        difficulty: 1,
        choices: [
          { id: 'a', text: 'Andante', correct: true },
          { id: 'b', text: 'Presto' },
          { id: 'c', text: 'Allegro' },
          { id: 'd', text: 'Vivace' },
        ],
        explain: 'Andante literally means “walking” and indicates a moderate, steady tempo slower than allegro.',
      },
      {
        id: 'italian-tempo-01-q2',
        type: 'mcq',
        prompt: 'Which marking indicates a very fast tempo?',
        difficulty: 1,
        choices: [
          { id: 'a', text: 'Presto', correct: true },
          { id: 'b', text: 'Largo' },
          { id: 'c', text: 'Adagio' },
          { id: 'd', text: 'Andante' },
        ],
        explain: 'Presto is among the fastest common tempo indications, faster than allegro and vivace in most classical usage.',
      },
    ],
  },
  {
    id: 'italian-dynamics-01',
    title: 'Dynamic Markings: From Pianissimo to Fortissimo',
    track: 'italian',
    kind: 'theory_lesson',
    difficulty: 1,
    tags: ['dynamics', 'italian', 'expression'],
    prerequisites: [],
    estimateMinutes: 4,
    body: 'Dynamic markings tell performers how loud or soft to play. Piano (p) means soft; forte (f) means loud. Doubling the letter intensifies the effect: pianissimo (pp) is very soft, fortissimo (ff) very loud. Mezzo (m) means “moderately”: mezzo piano (mp) is moderately soft, mezzo forte (mf) is moderately loud — often the default speaking volume in ensemble playing.\n\nCrescendo (gradually louder) and diminuendo or decrescendo (gradually softer) shape phrases over several bars. A sudden accent is marked sf or sfz (sforzando). In trad music, dynamics are rarely written note-for-note, but good players still breathe crescendi into long notes and lighten repeated figures to avoid monotony.\n\nDynamics interact with articulation and tempo: a reel played mf with crisp bowing feels different from the same tune played mp with more sustain. When arranging for céilí band or session recording, marking a few strategic dynamic changes can clarify tune changes and set off solo passages.',
    tryThis: '',
    quizzes: [
      {
        id: 'italian-dynamics-01-q1',
        type: 'mcq',
        prompt: 'What does “mf” stand for?',
        difficulty: 1,
        choices: [
          { id: 'a', text: 'Mezzo forte (moderately loud)', correct: true },
          { id: 'b', text: 'Molto forte (very loud)' },
          { id: 'c', text: 'Mezzo piano (moderately soft)' },
          { id: 'd', text: 'Minor fortissimo' },
        ],
        explain: 'mf means mezzo forte — moderately loud, a common default dynamic in ensemble and solo playing.',
      },
      {
        id: 'italian-dynamics-01-q2',
        type: 'truefalse',
        prompt: 'A crescendo marking means to gradually get louder.',
        difficulty: 1,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Crescendo (often abbreviated cresc.) indicates a steady increase in volume over the marked passage.',
      },
    ],
  },
  {
    id: 'italian-articulation-01',
    title: 'Articulation Marks: Legato, Staccato, and Accents',
    track: 'italian',
    kind: 'theory_lesson',
    difficulty: 2,
    tags: ['articulation', 'italian', 'technique'],
    prerequisites: [],
    estimateMinutes: 4,
    body: 'Articulation marks describe how notes connect or separate. Legato means smooth and connected; staccato means detached, with space between notes. A slur curves over notes that should be played in one breath or bow stroke without re-articulating each pitch. A dot above or below a notehead also indicates staccato in many styles.\n\nAccents (>) stress individual notes within a phrase. Tenuto (—) asks for full value and slight emphasis. Marcato suggests a marked, emphatic attack. Trills, mordents, and turns are ornament signs common in classical sources and some baroque-influenced trad settings, though Irish ornamentation is often learned by ear rather than from symbols.\n\nFor string players, articulation is largely bowing: same-note re-bowing versus slurring changes the dance feel of a reel entirely. Wind players use tonguing patterns (doo-doo vs doo-goo). Matching articulation to dance type — crisp for reels, slightly more legato for airs — is as important as playing the right notes.',
    tryThis: '',
    quizzes: [
      {
        id: 'italian-articulation-01-q1',
        type: 'mcq',
        prompt: 'What does “legato” mean?',
        difficulty: 2,
        choices: [
          { id: 'a', text: 'Smooth and connected', correct: true },
          { id: 'b', text: 'Short and detached' },
          { id: 'c', text: 'Very loud' },
          { id: 'd', text: 'Gradually slower' },
        ],
        explain: 'Legato indicates that notes should flow into one another without noticeable gaps between attacks.',
      },
      {
        id: 'italian-articulation-01-q2',
        type: 'mcq',
        prompt: 'A slur marking over several notes indicates:',
        difficulty: 2,
        choices: [
          { id: 'a', text: 'Play the notes in one connected gesture without re-articulating each one', correct: true },
          { id: 'b', text: 'Play each note with a heavy accent' },
          { id: 'c', text: 'Repeat the notes in a loop' },
          { id: 'd', text: 'Play the passage an octave higher' },
        ],
        explain: 'A slur connects the covered notes into a single phrase, using one bow stroke, breath, or tonguing pattern.',
      },
    ],
  },
  {
    id: 'italian-form-01',
    title: 'Form Labels: D.C., D.S., Coda, and Fine',
    track: 'italian',
    kind: 'theory_lesson',
    difficulty: 2,
    tags: ['form', 'italian', 'notation'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Italian form directions tell you how to navigate repeats and endings in longer pieces. Da capo (D.C.) means “from the head” — return to the beginning. Da capo al fine means play from the start until you reach fine (“end”). Dal segno (D.S.) means “from the sign” (the segno symbol), often skipping an opening section on the repeat.\n\nCoda designates a concluding section reached only after a jump marked “To Coda” or via a D.S. al coda instruction. Understanding these signs prevents you from stopping too early in a set piece or classical arrangement of a trad tune. In simpler dance tunes, first and second endings (1. / 2.) accomplish a similar job with less Italian vocabulary.\n\nMany session tunes use AABB or AB form without written navigation signs, but printed collections of O’Carolan pieces, hornpipe variants, and céilí set arrangements routinely include D.C. and D.S. markings. Reading them confidently keeps you aligned with the rest of the ensemble on the repeat.',
    tryThis: '',
    quizzes: [
      {
        id: 'italian-form-01-q1',
        type: 'mcq',
        prompt: 'What does “D.C. al fine” mean?',
        difficulty: 2,
        choices: [
          { id: 'a', text: 'Return to the beginning and play until you reach “fine”', correct: true },
          { id: 'b', text: 'Skip to the coda immediately' },
          { id: 'c', text: 'Play the second ending only' },
          { id: 'd', text: 'Repeat the last four bars' },
        ],
        explain: 'Da capo al fine sends the performer back to the start (capo) and forward until the marking fine, then stop.',
      },
      {
        id: 'italian-form-01-q2',
        type: 'truefalse',
        prompt: '“D.S.” means to resume playing from the segno sign, not from the very beginning.',
        difficulty: 2,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Dal segno directs the player to the segno symbol placed earlier in the score, skipping material before that point on the repeat.',
      },
    ],
  },
]
