export default [
  {
    id: 'styles-baroque-01',
    title: 'Baroque Style: Ornament, Continuo, and Dance',
    track: 'styles',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['baroque', 'style', 'ornament'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Baroque music (roughly 1600–1750) favours continuous motion, clear bass lines, and figured-harmony accompaniment (basso continuo). Ornamentation is expected: trills, mordents, and appoggiaturas are not optional fluff but part of the style. Harpsichord and baroque violin treatises describe when to grace cadences and how to vary repeats.\n\nDance suites anchor much instrumental baroque repertoire — allemande, courante, sarabande, gigue — linking court culture to village dance roots. O’Carolan’s harp music and baroque flute arrangements of trad tunes sit in this world of patterned basses and melodic variation on the repeat.\n\nIf you play baroque-influenced sets, practise grounding tempo with a steady bass while melody ornaments lightly. Over-ornamenting early repeats leaves nowhere to go; save intensity for the second time through.',
    tryThis: '',
    quizzes: [
      {
        id: 'styles-baroque-01-q1',
        type: 'mcq',
        prompt: 'Basso continuo in baroque music refers to:',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'A bass line with harmonic figures filled in by keyboard or lute', correct: true },
          { id: 'b', text: 'A capo on the second fret' },
          { id: 'c', text: 'Unaccompanied solo whistle' },
          { id: 'd', text: 'Strictly percussion-only accompaniment' },
        ],
        explain: 'Continuo players realise chords from a bass line and figures, supporting melody instruments in baroque ensemble texture.',
      },
      {
        id: 'styles-baroque-01-q2',
        type: 'truefalse',
        prompt: 'Ornamentation was considered an expected part of baroque performance practice.',
        difficulty: 4,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Baroque treatises document standard ornaments and when to apply them, especially on cadences and repeated sections.',
      },
    ],
  },
  {
    id: 'styles-classical-01',
    title: 'Classical Style: Balance and Sonata Form',
    track: 'styles',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['classical', 'style', 'form'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Classical-era music (roughly 1750–1820) values symmetry, homophonic texture (melody with accompaniment), and clearly articulated phrases. Sonata form — exposition, development, recapitulation — organises longer works, but the same question–answer phrase logic appears in short dance tunes and song verses.\n\nDynamic shading stays within classical norms: sudden forte surprises exist but less extreme than Romantic extremes. Alberti bass and broken-chord accompaniment patterns support singable top lines. String quartets from Haydn and Mozart model how four friends converse musically — a metaphor for good session listening.\n\nClassical clarity helps arrangers of trad tunes: if everyone ornaments differently at once, texture muddies. Classical balance suggests varying one layer at a time while others hold steady.',
    tryThis: '',
    quizzes: [
      {
        id: 'styles-classical-01-q1',
        type: 'mcq',
        prompt: 'Classical texture often features:',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'A clear melody with accompaniment (homophony)', correct: true },
          { id: 'b', text: 'Only unstructured noise' },
          { id: 'c', text: 'Exclusive use of 7/8 meter' },
          { id: 'd', text: 'No phrase structure at all' },
        ],
        explain: 'Classical style typically foregrounds a primary melody supported by simpler harmonic accompaniment.',
      },
      {
        id: 'styles-classical-01-q2',
        type: 'mcq',
        prompt: 'Sonata form includes which large sections?',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'Exposition, development, recapitulation', correct: true },
          { id: 'b', text: 'Intro, verse, chorus, bridge only' },
          { id: 'c', text: 'Only a coda with no main material' },
          { id: 'd', text: 'Twelve-bar blues exclusively' },
        ],
        explain: 'Sonata form presents themes, develops them through key change and fragmentation, then returns in the home key.',
      },
    ],
  },
  {
    id: 'styles-romantic-01',
    title: 'Romantic Style: Expression and Expanded Harmony',
    track: 'styles',
    kind: 'theory_lesson',
    difficulty: 5,
    tags: ['romantic', 'style', 'expression'],
    prerequisites: [],
    estimateMinutes: 5,
    body: 'Romantic music (19th century) stretches forms for emotional narrative: bigger orchestras, richer chromatic harmony, and virtuoso solo writing. Chopin nocturnes, Brahms intermezzi, and Liszt transcriptions show harmony colouring mood as much as defining function.\n\nFolk players feel Romantic influence in slow air arrangements with lush piano introductions, key changes for drama in céilí band sets, and vibrato-heavy string treatment of song melodies. Nationalist composers (Dvořák, Grieg) embedded folk dances in symphonic guise, legitimising trad sources for concert audiences.\n\nRomantic harmony tools — borrowed chords, augmented sixths, extended dominants — appear sparingly in trad but colour contemporary folk songwriting. Use them where the story needs shadow; not every reel wants a Rachmaninoff ending.',
    tryThis: '',
    quizzes: [
      {
        id: 'styles-romantic-01-q1',
        type: 'mcq',
        prompt: 'Romantic-era music is often characterised by:',
        difficulty: 5,
        choices: [
          { id: 'a', text: 'Expanded emotional expression and richer harmony', correct: true },
          { id: 'b', text: 'Strict avoidance of all dynamics' },
          { id: 'c', text: 'Exclusive use of plainchant' },
          { id: 'd', text: 'No solo instrumental roles' },
        ],
        explain: 'Romantic composers pursued personal expression through larger forces, chromatic harmony, and virtuosic writing.',
      },
      {
        id: 'styles-romantic-01-q2',
        type: 'truefalse',
        prompt: 'Nationalist Romantic composers sometimes incorporated folk dance material into orchestral works.',
        difficulty: 5,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Composers like Dvořák and Grieg quoted folk melodies and dances, bridging oral tradition and concert hall.',
      },
    ],
  },
  {
    id: 'styles-folk-dances-01',
    title: 'Reels, Jigs, Waltzes, and Hornpipes',
    track: 'styles',
    kind: 'theory_lesson',
    difficulty: 2,
    tags: ['dance', 'reel', 'jig', 'waltz', 'hornpipe'],
    prerequisites: ['foundations-rhythm-01'],
    estimateMinutes: 6,
    body: 'Irish and Scottish session dance types each carry a distinct pulse. Reels are in 2/2 or 4/4 with a steady driving beat — think “ONE-two THREE-four” at moderate to fast tempo. Double jigs are in 6/8 with two beats per bar grouped as three eighth notes each: “JIG-ged-y JIG-ged-y.” Single jigs and slides use 12/8 variants in some regions.\n\nWaltzes sit in 3/4 with a strong first beat: “ONE-two-three.” Hornpipes often use dotted rhythm (long-short pairs) and swing, commonly notated in 4/4 with a slower, bouncy feel. Not every hornpipe is dotted in every region, but the caricature long-short pattern is a reliable clue when learning by ear.\n\nMatching your foot tap to the dance type prevents dragging a reel like a jig. When joining a set, listen one round for meter before playing — the best session etiquette you can bring.',
    tryThis: '',
    quizzes: [
      {
        id: 'styles-folk-dances-01-q1',
        type: 'mcq',
        prompt: 'A standard double jig is most commonly notated in:',
        difficulty: 2,
        choices: [
          { id: 'a', text: '6/8 time', correct: true },
          { id: 'b', text: '3/4 waltz time' },
          { id: 'c', text: '5/4 time' },
          { id: 'd', text: '7/8 exclusively' },
        ],
        explain: 'Double jigs use compound 6/8 meter with two main beats per bar, each subdivided into three eighth notes.',
      },
      {
        id: 'styles-folk-dances-01-q2',
        type: 'mcq',
        prompt: 'Which dance type is typically associated with a steady 2/2 or 4/4 drive?',
        difficulty: 2,
        choices: [
          { id: 'a', text: 'Reel', correct: true },
          { id: 'b', text: 'Waltz' },
          { id: 'c', text: 'Double jig' },
          { id: 'd', text: 'Slow air only' },
        ],
        explain: 'Reels move in duple meter with an even, propulsive rhythm distinct from triple-time jigs and waltzes.',
      },
    ],
  },
  {
    id: 'styles-blues-01',
    title: 'Blues: Form, Scale, and Expression',
    track: 'styles',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['blues', 'form', 'scale'],
    prerequisites: ['chords-sevenths-01'],
    estimateMinutes: 5,
    body: 'Blues combines a repeating harmonic form, a distinctive scale, and expressive microtonal inflection. Twelve-bar blues cycles I–IV–V chords (often dominant sevenths) over twelve bars with standard turnarounds. Eight-bar and sixteen-bar blues variants appear in regional styles.\n\nThe blues scale adds a lowered third, lowered fifth, and lowered seventh to the minor pentatonic, allowing “between the cracks” pitches on guitar and voice. Bent notes mimic vocal cry — parallel to sean-nós pitch inflection and fiddle slides.\n\nBlues intersects folk when Appalachian ballads meet African American song forms, and when trad bands add shuffle rhythm to hornpipes. Knowing the twelve-bar map helps you jam on a three-chord song at a pub without a chart.',
    tryThis: '',
    quizzes: [
      {
        id: 'styles-blues-01-q1',
        type: 'mcq',
        prompt: 'Classic twelve-bar blues primarily uses which harmonic functions?',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'I, IV, and V (often as dominant seventh chords)', correct: true },
          { id: 'b', text: 'Only minor ii chords' },
          { id: 'c', text: 'Strictly one chord for all twelve bars' },
          { id: 'd', text: 'Only diminished seventh chains' },
        ],
        explain: 'Twelve-bar blues rotates through tonic, subdominant, and dominant harmonies in a familiar repeating pattern.',
      },
      {
        id: 'styles-blues-01-q2',
        type: 'truefalse',
        prompt: 'Blue notes often involve flattened third and seventh degrees with expressive pitch bending.',
        difficulty: 4,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Blues inflection lowers certain scale degrees and bends pitch for expressive effect beyond fixed equal temperament.',
      },
    ],
  },
  {
    id: 'styles-jazz-01',
    title: 'Jazz Basics: Swing, Standards, and Changes',
    track: 'styles',
    kind: 'theory_lesson',
    difficulty: 5,
    tags: ['jazz', 'swing', 'standards'],
    prerequisites: ['styles-blues-01', 'chords-sevenths-01'],
    estimateMinutes: 6,
    body: 'Jazz grew from blues, ragtime, and brass band traditions into a music centred on swing feel, improvisation, and chord progression literacy. Musicians learn standards (“Autumn Leaves,” “All the Things You Are”) to share repertoire without sheet music, much as trad players share tune titles at sessions.\n\nLead sheets give melody and chord symbols; the rest is improvised. ii–V–I motion, tritone substitutions, and turnarounds appear constantly. Rhythm sections walk bass, comp chords on offbeats, and ride cymbal patterns define swing at medium tempo.\n\nFolk-jazz crossover uses jazz voicings on song accompaniment or adds improvised choruses between tune repeats. You do not need bebop velocity to participate — outline chord roots on strong beats and listen for where the soloist goes.',
    tryThis: '',
    quizzes: [
      {
        id: 'styles-jazz-01-q1',
        type: 'mcq',
        prompt: 'A typical jazz “lead sheet” provides:',
        difficulty: 5,
        choices: [
          { id: 'a', text: 'Melody and chord symbols, with improvisation expected', correct: true },
          { id: 'b', text: 'Fully written orchestral score with no improvisation' },
          { id: 'c', text: 'Lyrics only' },
          { id: 'd', text: 'Tablature without chord names' },
        ],
        explain: 'Lead sheets are shorthand: head melody plus changes, leaving arrangement and soloing to the performers.',
      },
      {
        id: 'styles-jazz-01-q2',
        type: 'mcq',
        prompt: 'ii–V–I progression is central to jazz because:',
        difficulty: 5,
        choices: [
          { id: 'a', text: 'It creates strong harmonic motion toward the tonic', correct: true },
          { id: 'b', text: 'It avoids all dominant chords' },
          { id: 'c', text: 'It replaces melody entirely' },
          { id: 'd', text: 'It only works in 6/8 jig time' },
        ],
        explain: 'Minor ii to dominant V resolving to I is the workhorse cadential pattern in jazz harmony.',
      },
    ],
  },
  {
    id: 'styles-pop-01',
    title: 'Pop Song Craft: Hooks, Verse-Chorus, and Production',
    track: 'styles',
    kind: 'theory_lesson',
    difficulty: 3,
    tags: ['pop', 'songwriting', 'form'],
    prerequisites: ['chords-diatonic-major-01'],
    estimateMinutes: 5,
    body: 'Popular song since the 20th century favours memorable hooks, verse–chorus form, and repeated four-chord loops (I–V–vi–IV and variants). Folk singers borrow pop craft when writing originals or arranging trad songs for wider audiences — tight intros, clear choruses, and dynamic build into final chorus.\n\nProduction choices — acoustic versus electric instrumentation, doubling vocals, percussion entry on chorus — shape listener experience as much as harmony. Spotify-era folk often strips to guitar-vocal verse then adds bodhrán and fiddle on chorus for lift.\n\nUnderstanding pop form helps you cut a long ballad for a festival slot or place a trad tune in a set with pacing: slow verse-like intro, dance tune as “chorus energy,” return to song for balance.',
    tryThis: '',
    quizzes: [
      {
        id: 'styles-pop-01-q1',
        type: 'mcq',
        prompt: 'Which progression is a common pop four-chord loop in major keys?',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'I–V–vi–IV', correct: true },
          { id: 'b', text: 'Only vii°–I repeated' },
          { id: 'c', text: 'Strictly IV–IV–IV–IV' },
          { id: 'd', text: 'No chords, drone only' },
        ],
        explain: 'I–V–vi–IV (and rotations like vi–IV–I–V) underpins countless pop and folk-rock songs.',
      },
      {
        id: 'styles-pop-01-q2',
        type: 'truefalse',
        prompt: 'Verse–chorus form alternates narrative sections with a repeated, high-energy chorus.',
        difficulty: 3,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Pop songs typically contrast detailed verses with a catchy, repeatable chorus hook.',
      },
    ],
  },
  {
    id: 'styles-modes-01',
    title: 'Modes in Folk Practice',
    track: 'styles',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['modes', 'dorian', 'mixolydian'],
    prerequisites: ['scales-major-01', 'transpose-modes-01'],
    estimateMinutes: 5,
    body: 'Modes explain tunes that do not behave like textbook major or minor. Dorian has minor third but major sixth (D dorian: D E F G A B C D). Mixolydian has major third but lowered seventh (G mixolydian: G A B C D E F G). Aeolian matches natural minor; ionian matches major.\n\nIrish repertoire uses dorian and mixolydian colours constantly: “Banish Misfortune” is often analysed as A dorian; many D-centred tunes use C natural (mixolydian on D). Players describe these as “minor with a major sixth” or “major with a flat seventh” without Greek names — modes give the shared vocabulary.\n\nHarmonising modal tunes works best when you respect the characteristic note: do not sharp C in D mixolydian just because D major would. Mode-aware backup keeps sessions sounding authentic.',
    tryThis: '',
    quizzes: [
      {
        id: 'styles-modes-01-q1',
        type: 'mcq',
        prompt: 'D dorian differs from D natural minor by having:',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'A major sixth (B natural instead of B♭)', correct: true },
          { id: 'b', text: 'A lowered third' },
          { id: 'c', text: 'No fourth scale degree' },
          { id: 'd', text: 'An extra sharp on every note' },
        ],
        explain: 'Dorian keeps a minor third but raises the sixth degree compared to aeolian/natural minor.',
      },
      {
        id: 'styles-modes-01-q2',
        type: 'mcq',
        prompt: 'Mixolydian mode is like major except:',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'The seventh scale degree is lowered', correct: true },
          { id: 'b', text: 'The third is lowered to minor' },
          { id: 'c', text: 'The fifth is always absent' },
          { id: 'd', text: 'It uses 6/8 meter only' },
        ],
        explain: 'Mixolydian matches major on degrees 1–6 but lowers the seventh, giving a dominant-flavoured tonic chord.',
      },
    ],
  },
  {
    id: 'styles-modern-01',
    title: 'Modern and Contemporary Folk Fusion',
    track: 'styles',
    kind: 'theory_lesson',
    difficulty: 5,
    tags: ['modern', 'fusion', 'contemporary'],
    prerequisites: ['styles-jazz-01', 'styles-pop-01'],
    estimateMinutes: 5,
    body: 'Contemporary trad embraces electric instruments, loop pedals, minimalist repetition, and genre crossovers — Celtic punk, folktronica, Nordic folk metal, and acoustic singer-songwriter circuits. Groups like The Bothy Band, Altan, and Lankum (each in different eras) expanded harmony, instrumentation, and production while keeping tune cores recognisable.\n\nModern players sample archival field recordings, add synth pads under pipes, or write polymeter tunes that still launch a ceilidh dance. Copyright and credit matter more as tunes circulate on streaming platforms; citing composers and sources is part of modern practice.\n\nFusion succeeds when the trad pulse remains identifiable: if the reel groove survives the drum kit, the tune still calls dancers. Experiment outward from a solid unadorned version first — know the tradition you are stretching.',
    tryThis: '',
    quizzes: [
      {
        id: 'styles-modern-01-q1',
        type: 'mcq',
        prompt: 'Successful folk fusion typically:',
        difficulty: 5,
        choices: [
          { id: 'a', text: 'Keeps core trad rhythm and tune identity while adding new textures', correct: true },
          { id: 'b', text: 'Removes all dance pulse entirely' },
          { id: 'c', text: 'Avoids naming tune sources' },
          { id: 'd', text: 'Requires abandoning acoustic instruments always' },
        ],
        explain: 'Fusion works when listeners still recognise the trad skeleton — melody and dance groove — beneath new arrangement layers.',
      },
      {
        id: 'styles-modern-01-q2',
        type: 'truefalse',
        prompt: 'Modern trad artists may use loop pedals, electric instruments, and production techniques.',
        difficulty: 5,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Contemporary folk ensembles routinely blend traditional repertoire with modern gear and studio production.',
      },
    ],
  },
]
