export default [
  {
    id: 'transpose-why-01',
    title: 'Why Transpose? Keys, Instruments, and Voices',
    track: 'transposition',
    kind: 'theory_lesson',
    difficulty: 2,
    tags: ['transposition', 'keys', 'instruments'],
    prerequisites: ['keys-circle-01'],
    estimateMinutes: 4,
    body: 'Transposition means moving a whole piece — melody and harmony — up or down by a fixed interval so it sounds in a different key. Players transpose to fit their instrument’s comfortable range, to match a singer’s voice, or to align with another musician who knows a tune only in D when the session is in G.\n\nSome instruments are transposing by convention: B♭ clarinet and trumpet parts are written so that when the player reads C, the concert pitch is B♭. Whistle and accordion players often think in written fingerings rather than concert pitch. Understanding whether you are talking about written or concert pitch prevents confusion at workshops and band rehearsals.\n\nTransposing does not change the tune’s internal relationships: intervals, contour, and harmonic functions stay the same. Only the absolute pitch shifts. That is why a reel learned in A can move to G without rewriting the melody’s shape — you are relocating the same pattern on the fingerboard or keyboard.',
    tryThis: '',
    quizzes: [
      {
        id: 'transpose-why-01-q1',
        type: 'mcq',
        prompt: 'What stays the same when you transpose a tune to a new key?',
        difficulty: 2,
        choices: [
          { id: 'a', text: 'The intervals and melodic shape', correct: true },
          { id: 'b', text: 'The absolute concert pitch of every note' },
          { id: 'c', text: 'The key signature only, not the notes' },
          { id: 'd', text: 'The time signature and bar count only' },
        ],
        explain: 'Transposition shifts all pitches equally, preserving intervals, contour, and harmonic relationships.',
      },
      {
        id: 'transpose-why-01-q2',
        type: 'truefalse',
        prompt: 'Players often transpose to match a singer’s comfortable range.',
        difficulty: 2,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Vocal range is a primary reason to move a song to a higher or lower key so the melody sits comfortably for the singer.',
      },
    ],
  },
  {
    id: 'transpose-melody-01',
    title: 'Transposing Melodies by Interval',
    track: 'transposition',
    kind: 'theory_lesson',
    difficulty: 3,
    tags: ['melody', 'intervals', 'transposition'],
    prerequisites: ['transpose-why-01', 'intervals-01'],
    estimateMinutes: 5,
    body: 'To transpose a melody, move every note by the same interval — up a tone from D to E major, down a perfect fourth from G to D, and so on. If the tune starts on D and you transpose up a whole step, every D becomes E, every F♯ becomes G♯, and the key signature gains two sharps instead of one.\n\nScale-degree thinking speeds this up: if the opening phrase begins on the fifth degree of G major (D), the same phrase in D major begins on A, the fifth of D. Many trad players transpose by interval on the fly rather than rewriting ABC, especially when switching whistle keys mid-set.\n\nAccidentals in the original must move with their notes. A C♮ in F major becomes D♮ when you transpose up a whole step to G major — not C♯ unless the harmonic context demands it. Checking the first and last notes plus the highest peak often confirms you landed in the right key.',
    tryThis: '',
    quizzes: [
      {
        id: 'transpose-melody-01-q1',
        type: 'mcq',
        prompt: 'Transposing a tune from G major up a major second lands in which key?',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'A major', correct: true },
          { id: 'b', text: 'D major' },
          { id: 'c', text: 'F major' },
          { id: 'd', text: 'E minor only (never major)' },
        ],
        explain: 'A major second (whole step) above G is A; the key signature adds one sharp (G major has F♯, A major adds C♯).',
      },
      {
        id: 'transpose-melody-01-q2',
        type: 'mcq',
        prompt: 'When transposing by interval, you should:',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'Move every note (including accidentals) by the same interval', correct: true },
          { id: 'b', text: 'Move only the first note of each bar' },
          { id: 'c', text: 'Change the rhythm but keep pitch names' },
          { id: 'd', text: 'Transpose only notes on strong beats' },
        ],
        explain: 'Consistent interval shift preserves the melody; selective moves would distort intervals and harmony.',
      },
    ],
  },
  {
    id: 'transpose-chords-01',
    title: 'Transposing Chord Progressions',
    track: 'transposition',
    kind: 'theory_lesson',
    difficulty: 4,
    tags: ['chords', 'transposition', 'Nashville'],
    prerequisites: ['transpose-melody-01', 'chords-diatonic-major-01'],
    estimateMinutes: 5,
    body: 'Chord progressions transpose by moving every chord symbol the same distance. A I–V–vi–IV loop in G (G–D–Em–C) becomes A–E–F♯m–D in A when moved up a whole step. Roman numerals describe the functions, so the same chart works in any major key once you know the local I, IV, V, and vi triads.\n\nNashville Number System labels chords 1–7 by scale degree, independent of letter names. “1–5–6m–4” in D is D–A–Bm–G; in G it is G–D–Em–C. Session guitarists often call changes by number when a singer requests a new key between verses.\n\nWatch for chords that are not diatonic: a borrowed ♭VII or secondary dominant moves with the same interval as diatonic chords. Slash chords (G/B) transpose by shifting both the harmony and the bass note. Capo players mentally transpose: shapes in C with capo 2 sound in D.',
    tryThis: '',
    quizzes: [
      {
        id: 'transpose-chords-01-q1',
        type: 'mcq',
        prompt: 'I–V–vi–IV in the key of C is C–G–Am–F. What is the same progression in G major?',
        difficulty: 4,
        choices: [
          { id: 'a', text: 'G–D–Em–C', correct: true },
          { id: 'b', text: 'G–C–D–Em' },
          { id: 'c', text: 'G–A–Bm–D' },
          { id: 'd', text: 'Em–C–G–D' },
        ],
        explain: 'Each Roman numeral maps to its scale degree: I=G, V=D, vi=Em, IV=C in G major.',
      },
      {
        id: 'transpose-chords-01-q2',
        type: 'truefalse',
        prompt: 'The Nashville Number System labels chords by scale degree rather than letter name.',
        difficulty: 4,
        choices: [
          { id: 'true', text: 'True', correct: true },
          { id: 'false', text: 'False' },
        ],
        explain: 'Numbers 1–7 represent chord roots by major-scale degree, making transposition a matter of mapping to the new key.',
      },
    ],
  },
  {
    id: 'transpose-capo-01',
    title: 'Capo Logic for Guitar and Mandolin',
    track: 'transposition',
    kind: 'theory_lesson',
    difficulty: 3,
    tags: ['capo', 'guitar', 'practical'],
    prerequisites: ['transpose-chords-01'],
    estimateMinutes: 4,
    body: 'A capo shortens the vibrating string length, raising pitch without changing chord shapes. If you play G–C–D shapes with capo on the second fret, the sounding key is A major — each chord name moves up a whole step. Capo 3 from G shapes sounds B♭; capo 5 from G sounds C.\n\nCapo choice balances open-string resonance against vocal range. Folk guitarists often prefer familiar open chords (C, G, D, Em, Am) and capo to match the singer. Partial capos and cut capos create alternate tunings without retuning all strings, useful for drone effects in accompaniment.\n\nRemember: chord diagrams show finger shapes; the sounding key is shapes plus capo fret. Tell the band “capo 2, playing G shapes in A” to avoid mismatch with concert-pitch instruments. ABC and printed scores are usually in concert pitch unless marked otherwise.',
    tryThis: '',
    quizzes: [
      {
        id: 'transpose-capo-01-q1',
        type: 'mcq',
        prompt: 'G-major chord shapes with a capo on fret 2 sound in which key?',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'A major', correct: true },
          { id: 'b', text: 'G major (unchanged)' },
          { id: 'c', text: 'B major' },
          { id: 'd', text: 'E major' },
        ],
        explain: 'Each fret raises pitch by a semitone; two frets (capo 2) raise G shapes by a whole step to A.',
      },
      {
        id: 'transpose-capo-01-q2',
        type: 'mcq',
        prompt: 'Why do guitarists use a capo instead of only barre chords?',
        difficulty: 3,
        choices: [
          { id: 'a', text: 'To keep open-chord resonance and easier fingerings in a higher key', correct: true },
          { id: 'b', text: 'To lower the pitch below standard tuning' },
          { id: 'c', text: 'To change the time signature' },
          { id: 'd', text: 'To mute all strings permanently' },
        ],
        explain: 'Capo lets players use comfortable open voicings while sounding in a higher concert key suited to voice or ensemble.',
      },
    ],
  },
  {
    id: 'transpose-modes-01',
    title: 'Modes and Modal Transposition',
    track: 'transposition',
    kind: 'theory_lesson',
    difficulty: 7,
    tags: ['modes', 'dorian', 'mixolydian'],
    prerequisites: ['scales-major-01', 'transpose-melody-01'],
    estimateMinutes: 6,
    body: 'Modes are scales built by starting on different degrees of the major scale. D dorian (D E F G A B C D) shares the key signature of C major but centres on D. G mixolydian (G A B C D E F G) shares C major’s signature but centres on G with a lowered seventh (F instead of F♯).\n\nModal thinking helps explain tunes that seem “in major” but avoid leading-tone cadences. Many Irish melodies in D mixolydian use C natural against a D centre; A dorian tunes use G natural in a context that feels like A minor with a major IV chord. Transposing modally means preserving which scale degrees are altered, not just shifting letter names.\n\nWhen moving a modal tune to a new key, keep the same intervallic colour: dorian keeps major 6th and minor 3rd relative to the tonic; mixolydian keeps minor 7th and major 3rd. Session players often describe these as “D with a flat C” rather than naming the mode, but the theory clarifies why certain accidentals persist across transpositions.',
    tryThis: '',
    quizzes: [
      {
        id: 'transpose-modes-01-q1',
        type: 'mcq',
        prompt: 'D dorian has the same key signature as which major key?',
        difficulty: 7,
        choices: [
          { id: 'a', text: 'C major (no sharps or flats)', correct: true },
          { id: 'b', text: 'D major (two sharps)' },
          { id: 'c', text: 'F major (one flat)' },
          { id: 'd', text: 'G major (one sharp)' },
        ],
        explain: 'Dorian on D uses the white-key collection starting on D, matching C major’s key signature.',
      },
      {
        id: 'transpose-modes-01-q2',
        type: 'mcq',
        prompt: 'Which scale degree is lowered in mixolydian compared to major?',
        difficulty: 7,
        choices: [
          { id: 'a', text: 'Seventh (minor seventh above tonic)', correct: true },
          { id: 'b', text: 'Third (making it minor)' },
          { id: 'c', text: 'Fourth (making it augmented)' },
          { id: 'd', text: 'Fifth (making it diminished)' },
        ],
        explain: 'Mixolydian differs from major by a lowered seventh scale degree, giving a dominant-seventh colour on the tonic chord.',
      },
    ],
  },
]
