export default {
        'begged borrowed and stolen': {group:'Collections', link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/beggedborrowedandstolen.jpeg', book:"begged borrowed and stolen"},
        //'the campbell session': {link:'https://tunebook.net/scrape/campbell session.abc'},
        'jims roots and blues': {group:'Collections',link:'https://tunebook.net/scrape/jims roots.abc', image:'/book_images/jimsrootsandblues.jpeg'},
        'christmas songs': {group:'Collections',link:'https://tunebook.net/scrape/steve song book.abc', book: "christmas songs" ,image:'/book_images/christmassongs.jpeg'},
        'kids songs': {group:'Collections',link:'https://tunebook.net/scrape/steve song book.abc', book:"kids songs",  image:'/book_images/kidssongs.jpeg'},
        'steve song book': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/stevesongbook.jpeg', book:"steve song book"},
        'steve tunes': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/stevetunes.jpeg', book:"steve tunes"},
        'max': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/max.jpeg', book:"max"},
        'max new tunes': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/maxnewtunes.jpeg', book:"max new tunes"},
        'charlotte songs': {group:'Friends',link:'https://tunebook.net/scrape/charlotte songs.abc', image:'/book_images/charlotte.jpeg', book:"charlotte songs"},
        'charlotte originals': {group:'Friends',link:'https://tunebook.net/scrape/charlotte originals.abc', image:'/book_images/charlotteoriginals.jpeg', book:"charlotte originals"},
        'velma': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/velma.jpeg', book:"velma"},
        'fiona': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/velma.jpeg', book:"fiona"},
        'brooke': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/brooke.jpeg', book:"brooke"},
        'andrew': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/andrew.jpeg', book:"andrew"},
        'nick': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/nick.jpeg', book:"nick"},
        'ralph': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/ralph.jpeg', book:"ralph"},
        'cassidy': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/cassidy.jpeg', book:"cassidy"},
        'leila': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/leila.jpeg', book:"leila"},
        'mandira': {group:'Friends',link:'https://tunebook.net/scrape/mandira.abc', image:'/book_images/mandira.jpeg', book:"mandira"},
        'bhavit': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/bhavit.jpeg', book:"bhavit"},
        'steve\s whole songbook (live)': {googleDocumentId: '1ob9DTfROfBzIzON2cnIceQtmynt14Gnl', image:'/book_images/steve.jpeg'},
        'kameruka choir': {group:'Communities', link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/kamerukachoir.jpeg', book:"kameruka choir"},
        'kameruka bush dance': {group:'Communities', link:'https://tunebook.net/scrape/steve song book.abc'},
        'sean kenan irish music': {group:'Collections', link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/seankenanirishmusic.jpeg', book:"sean kenan irish music"},
        
        //'fred': {link: '1ob9DTfROfBzIzON2cnIceQtmynt14Gnl'},
}
