export default {
        'begged borrowed and stolen': {group:'Collections', link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/beggedborrowedandstolen.jpg', book:"begged borrowed and stolen"},
        //'the campbell session': {link:'https://tunebook.net/scrape/campbell session.abc'},
        'jims roots and blues': {group:'Collections',link:'https://tunebook.net/scrape/jims roots.abc', image:'/book_images/jimsrootsandblues.jpg'},
        'christmas songs': {group:'Collections',link:'https://tunebook.net/scrape/steve song book.abc', book: "christmas songs" ,image:'/book_images/christmassongs.jpg'},
        'kids songs': {group:'Collections',link:'https://tunebook.net/scrape/steve song book.abc', book:"kids songs",  image:'/book_images/kidssongs.jpg'},
        'steve song book': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/stevesongbook.jpg', book:"steve song book"},
        'steve tunes': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/stevetunes.jpg', book:"steve tunes"},
        'max': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/max.jpg', book:"max"},
        'max new tunes': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/maxnewtunes.jpg', book:"max new tunes"},
        'charlotte songs': {group:'Friends',link:'https://tunebook.net/scrape/charlotte songs.abc', image:'/book_images/charlotte.jpg', book:"charlotte songs"},
        'charlotte originals': {group:'Friends',link:'https://tunebook.net/scrape/charlotte originals.abc', image:'/book_images/charlotteoriginals.jpg', book:"charlotte originals"},
        'velma': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/velma.jpg', book:"velma"},
        'fiona': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/velma.jpg', book:"fiona"},
        'brooke': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/brooke.jpg', book:"brooke"},
        'andrew': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/andrew.jpg', book:"andrew"},
        'nick': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/nick.jpg', book:"nick"},
        'ralph': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/ralph.jpg', book:"ralph"},
        'cassidy': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/cassidy.jpg', book:"cassidy"},
        'leila': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/leila.jpg', book:"leila"},
        'mandeira': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/mandeira.jpg', book:"mandeira"},
        'bhavit': {group:'Friends',link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/bhavit.jpg', book:"bhavit"},
        'steve\s whole songbook (live)': {googleDocumentId: '1ob9DTfROfBzIzON2cnIceQtmynt14Gnl', image:'/book_images/steve.jpg'},
        'kameruka choir': {group:'Communities', link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/kamerukachoir.jpg', book:"kameruka choir"},
        'kameruka bush dance': {group:'Communities', link:'https://tunebook.net/scrape/steve song book.abc'},
        'sean kenan irish music': {group:'Collections', link:'https://tunebook.net/scrape/steve song book.abc', image:'/book_images/seankenanirishmusic.jpg', book:"sean kenan irish music"},
        
        //'fred': {link: '1ob9DTfROfBzIzON2cnIceQtmynt14Gnl'},
}
