/** Generated by scripts/lesson_plans/export_feed_from_lessons.py — do not edit by hand. */

import africa_comparative from './africa-comparative.js'
import africa_diaspora from './africa-diaspora.js'
import africa_diaspora_music from './africa-diaspora-music.js'
import africa_ghana from './africa-ghana.js'
import africa_guinea from './africa-guinea.js'
import africa_mali from './africa-mali.js'
import africa_nigeria from './africa-nigeria.js'
import asia_china from './asia-china.js'
import asia_comparative from './asia-comparative.js'
import asia_diaspora from './asia-diaspora.js'
import asia_japan from './asia-japan.js'
import asia_korea from './asia-korea.js'
import asia_mainland_se from './asia-mainland-se.js'
import asia_mongolia from './asia-mongolia.js'
import british_comparative from './british-comparative.js'
import british_diaspora from './british-diaspora.js'
import british_england from './british-england.js'
import british_morris from './british-morris.js'
import british_northumbria from './british-northumbria.js'
import british_song from './british-song.js'
import celtic_brittany from './celtic-brittany.js'
import celtic_comparative from './celtic-comparative.js'
import celtic_diaspora from './celtic-diaspora.js'
import celtic_ireland from './celtic-ireland.js'
import celtic_scotland from './celtic-scotland.js'
import celtic_wales from './celtic-wales.js'
import east_balkans from './east-balkans.js'
import east_baltic from './east-baltic.js'
import east_comparative from './east-comparative.js'
import east_diaspora from './east-diaspora.js'
import east_hungary from './east-hungary.js'
import east_klezmer from './east-klezmer.js'
import east_poland from './east-poland.js'
import french_acadian from './french-acadian.js'
import french_basque from './french-basque.js'
import french_comparative from './french-comparative.js'
import french_diaspora from './french-diaspora.js'
import french_louisiana_cajun from './french-louisiana-cajun.js'
import french_occitan from './french-occitan.js'
import french_quebec from './french-quebec.js'
import iberian_asturias from './iberian-asturias.js'
import iberian_castile_catalan from './iberian-castile-catalan.js'
import iberian_comparative from './iberian-comparative.js'
import iberian_diaspora from './iberian-diaspora.js'
import iberian_flamenco from './iberian-flamenco.js'
import iberian_galicia from './iberian-galicia.js'
import iberian_portugal from './iberian-portugal.js'
import latin_andes from './latin-andes.js'
import latin_brazil from './latin-brazil.js'
import latin_caribbean from './latin-caribbean.js'
import latin_comparative from './latin-comparative.js'
import latin_diaspora from './latin-diaspora.js'
import latin_mexico from './latin-mexico.js'
import latin_southern_cone from './latin-southern-cone.js'
import me_comparative from './me-comparative.js'
import me_diaspora from './me-diaspora.js'
import me_greece from './me-greece.js'
import me_levant from './me-levant.js'
import me_maghreb from './me-maghreb.js'
import me_persia from './me-persia.js'
import me_turkey from './me-turkey.js'
import nordic_comparative from './nordic-comparative.js'
import nordic_denmark from './nordic-denmark.js'
import nordic_diaspora from './nordic-diaspora.js'
import nordic_finland from './nordic-finland.js'
import nordic_islands from './nordic-islands.js'
import nordic_norway from './nordic-norway.js'
import nordic_sami from './nordic-sami.js'
import nordic_sweden from './nordic-sweden.js'
import roots_appalachia from './roots-appalachia.js'
import roots_bluegrass from './roots-bluegrass.js'
import roots_cajun from './roots-cajun.js'
import roots_comparative from './roots-comparative.js'
import roots_contra from './roots-contra.js'
import roots_diaspora from './roots-diaspora.js'
import roots_quebec from './roots-quebec.js'
import south_bengal from './south-bengal.js'
import south_carnatic from './south-carnatic.js'
import south_comparative from './south-comparative.js'
import south_diaspora from './south-diaspora.js'
import south_hindustani from './south-hindustani.js'
import south_india_folk from './south-india-folk.js'
import south_northwest from './south-northwest.js'

export default [
  ...africa_comparative,
  ...africa_diaspora,
  ...africa_diaspora_music,
  ...africa_ghana,
  ...africa_guinea,
  ...africa_mali,
  ...africa_nigeria,
  ...asia_china,
  ...asia_comparative,
  ...asia_diaspora,
  ...asia_japan,
  ...asia_korea,
  ...asia_mainland_se,
  ...asia_mongolia,
  ...british_comparative,
  ...british_diaspora,
  ...british_england,
  ...british_morris,
  ...british_northumbria,
  ...british_song,
  ...celtic_brittany,
  ...celtic_comparative,
  ...celtic_diaspora,
  ...celtic_ireland,
  ...celtic_scotland,
  ...celtic_wales,
  ...east_balkans,
  ...east_baltic,
  ...east_comparative,
  ...east_diaspora,
  ...east_hungary,
  ...east_klezmer,
  ...east_poland,
  ...french_acadian,
  ...french_basque,
  ...french_comparative,
  ...french_diaspora,
  ...french_louisiana_cajun,
  ...french_occitan,
  ...french_quebec,
  ...iberian_asturias,
  ...iberian_castile_catalan,
  ...iberian_comparative,
  ...iberian_diaspora,
  ...iberian_flamenco,
  ...iberian_galicia,
  ...iberian_portugal,
  ...latin_andes,
  ...latin_brazil,
  ...latin_caribbean,
  ...latin_comparative,
  ...latin_diaspora,
  ...latin_mexico,
  ...latin_southern_cone,
  ...me_comparative,
  ...me_diaspora,
  ...me_greece,
  ...me_levant,
  ...me_maghreb,
  ...me_persia,
  ...me_turkey,
  ...nordic_comparative,
  ...nordic_denmark,
  ...nordic_diaspora,
  ...nordic_finland,
  ...nordic_islands,
  ...nordic_norway,
  ...nordic_sami,
  ...nordic_sweden,
  ...roots_appalachia,
  ...roots_bluegrass,
  ...roots_cajun,
  ...roots_comparative,
  ...roots_contra,
  ...roots_diaspora,
  ...roots_quebec,
  ...south_bengal,
  ...south_carnatic,
  ...south_comparative,
  ...south_diaspora,
  ...south_hindustani,
  ...south_india_folk,
  ...south_northwest,
]
