/** Generated by scripts/lesson_plans/export_feed_from_lessons.py — do not edit by hand. */

import celtic_brittany from './celtic-brittany.js'
import celtic_comparative from './celtic-comparative.js'
import celtic_diaspora from './celtic-diaspora.js'
import celtic_ireland from './celtic-ireland.js'
import celtic_scotland from './celtic-scotland.js'
import celtic_wales from './celtic-wales.js'

export default [
  ...celtic_brittany,
  ...celtic_comparative,
  ...celtic_diaspora,
  ...celtic_ireland,
  ...celtic_scotland,
  ...celtic_wales,
]
